### ISSUE TITLE
[Bug] Enchants not persisting after tool upgrade

### ISSUE THREAD

**Issue by DYstebo** [mickelus/tetra#849] opened 2024-10-23 20:09 UTC
### Observed behaviour

Upgraded a pickaxe head side from bronze to iron, but the enchantments applied to the part went away.

### Expected behaviour

I found an issue in this github that said enchants were supposed to persist, but that is not the case. This may be a 'The Winter Rescue' modpack problem, but I want to make sure.

### Steps to reproduce

1. Make any pickaxe
2. Use workbench to make it a tetra pickaxe
3. Place enchant on pickaxe component with enchanted book
4. Replace component with another material of the same component type
5. Enchantment is lost

### Tetra version

3.20.0

### mutil/mGui version

3.3.0

### Forge version

1.16.5

### Other mods

The Winter Rescue modpack

**Comment by mickelus** [comment] 2024-10-28 20:32
Replacing the part with the enchantment makes the enchantment go away, this is intended behavior. Closing!

**Closed as completed by mickelus** 2024-10-28 20:32 UTC
Labels: bug
