### ISSUE TITLE
Gui bug

### ISSUE THREAD

**Issue by castilio20** [mickelus/tetra#301] opened 2021-01-04 20:59 UTC
![2021-01-04_22 52 44](https://user-images.githubusercontent.com/76228548/103578866-29497500-4e8c-11eb-97c6-6ec62dd69c2c.png)
i dont think i need to say more
overlapping

**Comment by mickelus** [comment] 2021-01-04 21:23
You still need to use the template for bug reports. Duplicate of #229, closing.

**Closed by mickelus** 2021-01-04 21:23 UTC

**Comment by castilio20** [comment] 2021-01-04 21:33
sorry about that  but will you fix the bug?
