### ISSUE TITLE
Unable to join server in 1.16.4-3.6.1 with Invalid State Exception

### ISSUE THREAD

**Issue by Dunkmania101** [mickelus/tetra#357] opened 2021-02-12 18:55 UTC
## Bug Report

**Observed Behaviour**
Upon attempting to join a server with version 1.16.4-3.6.1, I am almost immediately disconnected with a message describing "Invalid state exception: recursive loading of  INVALID-tetra:modular_double". This message doesn't seem to appear in any logs, so I had to put that from memory. The previous version didn't seem to have this error. Also, there were no crashes, just the inability to join the server.

**Expected Behaviour**
I should join the server like normal. I should note that I haven't tested this in single-player.

**Minimal setup needed to reproduce**
- Forge version: 1.16.5-36.0.22
- Tetra version: 1.16.4-3.6.1
- Other mods: There are other mods installed, although I suspect this is solely a tetra error as it seems to come from an item model, judging by the presence of an item model called "modular_double" in the source.

Sorry for the lack of info, there just wasn't much available to convey.

**Comment by mickelus** [comment] 2021-02-12 22:20
I need an exact modlist and the logs. I've seen others have a similar issue but I'm unable to reproduce it. I introduced some changes that makes it more obvious in 3.6.1, which is why you're getting "Invalid state exception: recursive loading of INVALID-tetra:modular_double".

**Comment by Dunkmania101** [comment] 2021-02-13 00:02
I didn't send the log in the original post because they didn't include any mention of an error on connecting, at least as far as I could see. I'll attach it here.

Out of curiosity, what kind of recursion is happening with that item model? Is it trying to render it in some kind of a loop? Multiple times? Or is that the mystery? I tried figuring it out for myself by reading through the code but didn't really understand what you were doing, probably from not having been a part of setting it up in the first place. Just wondering.

[debug.log](https://gist.github.com/Dunkmania101/c4bb8005cac2c25cf0487beceacdf7c1)
And, with the power of the ls command and double carrots:
[Modslist](https://gist.github.com/Dunkmania101/400d7be101611ff122e2674cfc528e24)

Thanks!

**Comment by mickelus** [comment] 2021-02-13 03:14
Possibly duplicate of #354 

Could you provide me with the server log as well?
Why it would be related to the item model?

**Comment by Dunkmania101** [comment] 2021-02-13 03:21
I thought the  "tetra:modular_double" resource location was for an item model. The only file I can see with that name is in the item models folder. As for being a duplicate, I'm not sure as my server didn't crash and there weren't any hammers in the world.

Here's the log:
[Debug.log](https://gist.github.com/Dunkmania101/963bb8bd8afba34a1427cc4ab93f26eb)

**Comment by mickelus** [comment] 2021-02-24 17:18
Closing, same issue as #365.

**Closed by mickelus** 2021-02-24 17:18 UTC
Labels: Needs refinement, bug

**Comment by Dunkmania101** [comment] 2021-02-24 18:22
Looks like it is the same cause, although my game never crashed, it just wouldn't connect to my server. The message in the crash log of that error looks pretty similar to the server disconnect message, so they're probably at least equivalent. I wonder what caused that difference. Anyway, good luck!
