### ISSUE TITLE
Honing double headed damage upgrade on axes stops adding damage

### ISSUE THREAD

**Issue by VallenFrostweaver** [mickelus/tetra#127] opened 2020-02-19 13:09 UTC
## Bug Report

**Observed Behaviour**
I was progressing "honing: damage" on a double headed iron axe with an end rod handle and string wraps. after progressing the honing: damage on one axe head to max I was going to start progressing the honing:damage on the other head but it actually doesn't add any damage and uses up the honing progress.

**Expected Behaviour**
To continue to add damage on second axe head when adding honing: damage bonus.

**Minimal setup needed to reproduce**
2-headed iron axe w/end rod handle and string binding. progress honing enough to get full Honing: Damage on one head and then progress on the other head and the damage will stop though the upgrade is still available to use.

- Forge version: 28.1.111
- Tetra version: 1.14.4-1.19.1
- Tetra configuration: n/a
- Other mods: lots but works with vanilla + tetra too for me

**Steps to reproduce**
see **Minimal setup needed to reproduce** though here's a screen shot showing the lack of damage it gives (and I tried with iron and diamond):
![bug 2](https://user-images.githubusercontent.com/13642054/74837290-12a03b00-5319-11ea-8cfc-9b82684420c2.png)

**Comment by mickelus** [comment] 2020-02-19 21:31
This is actually intended behaviour, but I've not explained it anywhere. Damage and capabilities/harvest tier & efficiency doesn't stack between tool heads. Things turned out so OP when it did so I had to change it. I should explain it in the advancements though!

**Comment by VallenFrostweaver** [comment] 2020-02-20 12:21
So are you saying that you aren't supposed to be able to upgrade damage on both heads of a 2 headed tool/weapon with honing?

**Comment by mickelus** [comment] 2020-03-05 19:24
Closing this! I've started on a series of tutorial advancements that exist purely to explain obscure concepts like this one!

**Closed by mickelus** 2020-03-05 19:24 UTC
