### ISSUE TITLE
Inventory Tweaks Renewed middle click sorting, causes item duplication in combination with Tetra's workbench.

### ISSUE THREAD

**Issue by LifusChrustus** [mickelus/tetra#445] opened 2021-06-10 10:53 UTC
## Bug Report

**Observed Behaviour**
By accident I discovered that by putting any item into modifying slot of Tetra's workbench, you can easily duplicate anything that happens to find itself in player's inventory. All because of inventory sorting method which - at first glance - seems to take advantage of menu generated with Tetra and mGUI. When said item is middle clicked while being placed in workbench slot, other things from player's inventory disappear and reappear after another click - this time in multiple, physical copies.

**Expected Behaviour**
Player's inventory sorts itself without item disappearing and duplicating.

**Minimal setup needed to reproduce**
- Forge version: 36.1.16
- Tetra version: 3.11.1
- Tetra configuration: Default Tetra configuration
- Other mods: Inventory Tweaks Renewed v1.16.4-1.0.1, mGUI v3.2.0

**Steps to reproduce**
1) Put any item in Tetra's workbench slot.
2) Have literally anything in your inventory/hotbar.
3) Middle double-click the item in previously mentioned slot.

**Comment by mickelus** [comment] 2021-06-10 11:20
Closing, duplicate of #431

**Closed by mickelus** 2021-06-10 11:20 UTC
