### ISSUE TITLE
[Bug] Netherite tetra pickaxe with extractor not recognized as netherite pickaxe

### ISSUE THREAD

**Issue by andrew-suh** [mickelus/tetra#844] opened 2024-10-01 08:21 UTC
### Observed behaviour

I'm currently in a Nether Catacomb and my netherite pickaxe cannot breakdown withered debris or any withered blocks. However, a normal vanilla netherite pickaxe can break them just fine.

### Expected behaviour

Expected a netherite tetra pickaxe with extractor sub head to break blocks like withered debris.
![Screenshot 2024-10-01 011327](https://github.com/user-attachments/assets/436ad99f-bd2b-4c25-817d-1831e2d169d5)
![Screenshot 2024-10-01 011336](https://github.com/user-attachments/assets/a70bf7b2-7282-4170-894c-6f27ef063f96)

### Steps to reproduce

1. Place vanilla netherite pickaxe on workplace bench
2. Add extractor sub head
3. Enchant with Unbreaking 4 and Eff. 6
4. Go to a Nether Catacomb
5. Unable to break Withered blocks.

### Tetra version

1.19.2-6.6.0

### mutil/mGui version

1.19.2-5.2.0

### Forge version

1.262.1-20597

**Comment by mickelus** [comment] 2024-11-25 19:53
A single headed pick is a tier lower than its double headed counterpart, so that's intended behaviour. Closing!

**Closed as completed by mickelus** 2024-11-25 19:53 UTC
Labels: bug
