### ISSUE TITLE
Getting many errors in crash log

### ISSUE THREAD

**Issue by Andyghandi** [mickelus/tetra#2] opened 2018-04-29 22:30 UTC
Im clogging up my launcher log with very many messages from this mod such as: 

Detected ongoing potential memory leak. 600 packets have leaked. Top offenders
--

Tetra: 600

And many chunk updates:

Tetra loaded a new chunk [479, 41] in dimension 0 (overworld) while populating chunk [479, 42], causing cascading worldgen lag.

Why is that? I know I can disable the logging but I just want to know if this would be a problem.

Really liking the approach of this mod btw.

Cheers

**Comment by mickelus** [comment] 2018-04-30 10:29
I'm using an old networking setup which is the cause of the potential memory leak warnings. There's a "new" networking setup available in fml, I intend to switch to that which should solve the potential leak. I have not had a server running for long enough to know if there's an actual leak, if your memory usage goes up over time then you can solve it by restarting the sever.

The cascading worldgen issue has been fixed and should be available in 0.7.0.

**Comment by Andyghandi** [comment] 2018-04-30 12:38
Will try that version when I get home! Btw Im very brand new to this mod. Will the geodes spawn in another terrain gen mod and how do I crack them open on the mk2 bench?

**Comment by mickelus** [comment] 2018-04-30 14:17
I hope I'll manage to release it before you get home then ;). Geodes generates everywhere before 0.7.0, after 0.7.0 they will generate where there's stone.
To break a geode, place it in the workbench and make sure you have a hammer in your inventory :)

**Comment by mickelus** [comment] 2018-05-10 12:18
The source of the memory leak warnings was fixed in 0.8.0, so I'm closing this!

**Closed by mickelus** 2018-05-10 12:18 UTC
