### ISSUE TITLE
bug, tetra breaks crafts with wood planks

### ISSUE THREAD

**Issue by Uvbnstrk2** [mickelus/tetra#780] opened 2023-12-10 10:11 UTC
### Observed behaviour

every recipe containing wood planks uses 2 in a slot making it uncraftable.

### Expected behaviour

normal recipes

### Steps to reproduce

load in
check recipes in jei

### Crashlog

N/A

### Tetra version

0.39.1

### mutil/mGui version

N/A

### Forge version

1.12.2

### Other mods

xaeros minimap, worldedit, AE2, AE2 wireless crafting terminal, twilight forest, thermal innovation, thermal foundation, thermal expantion, thermal dynamics, thaumic wands, thaumic terminal, thaumicJEI, thaumic augmentation, thaumic additions, thaumcraft, supermartin642 lib, somanyenchantments, rf tools dimensions, rf tools, redstone flux, potion fingers, placebo, password's lib, orespawn, not enough energistics, multitools, MMD lib, minetweakerrecipemaker, mcjty lib, mantle, llibrary, just enough energistics, jei, ice and fire, hwyla, ftb ultimine, foamfix, eye of dragons, extra cpus, enchanting plus, elevators, CoFH world, CoFH core, code chicken lib, chunkloaders, champions, censored asm, bring me the rings, bookshelf, oh the biomes you'll go, baubles, base metals, autoreg lib, apotheosis, alchemistry, draconic evolution, overloaded armor bar, project intelligence

**Comment by mickelus** [comment] 2023-12-22 10:48
Closing, duplicate of #134.

**Closed as completed by mickelus** 2023-12-22 10:48 UTC
Labels: bug
