### ISSUE TITLE
[Bug] Tetra not supporting oredict causes mod progression to cease

### ISSUE THREAD

**Issue by jrddunbr** [mickelus/tetra#464] opened 2021-07-10 23:45 UTC
### Observed behaviour

Loading a world with Create as rock strata (without regular Minecraft stone) prevents mod progress. Same with when there are non-vanilla woods.

### Expected behaviour

Oredict fallback for most woods and stones (the Create stones appear to have `forge:stone` for instance)

### Tetra version

Latest

### mGui version

Latest

### Forge version

1.16.5 Latest

### Other mods

Create, TerraForged, etc.

**Comment by mickelus** [comment] 2021-07-11 13:04
Closing:
* there's nothing that relies on players using regular stone
* there's no oredict in 1.16
* there's no version called "latest" (tetra, mgui, forge)
* required fields have been removed (crash log, steps to reproduce)
* "etc" is not a modlist

Comment on this issue once you've fixed the issues listed above and it'll be reopened.

**Closed by mickelus** 2021-07-11 13:04 UTC
Labels: bug

**Comment by jrddunbr** [comment] 2021-07-11 13:33
I'm going to be straight up, that is the most petty response I've ever received on GitHub.

I removed fields that were irrelevant to the issue because your template is incorrectly biased towards crashes. Most bugs will not be crashes, and so I removed fields that were not applicable to reduce noise. The fact that you're calling it out because you love your template is probably the stupidest thing I've seen all week.

Regardless, see below.

> there's nothing that relies on players using regular stone

So here's normal Minecraft cobblestone: (I've turned on F3-H here to show item information)

![2021-07-11_09 13 43](https://user-images.githubusercontent.com/14130505/125196690-c2d15500-e228-11eb-9d10-f86e6fd3e716.png)

Cool. That works. Now let's try Create and Oh, The Biomes You'll Go.

![2021-07-11_09 15 01](https://user-images.githubusercontent.com/14130505/125196728-e0062380-e228-11eb-958f-a5791ebf13e7.png)
![2021-07-11_09 14 13](https://user-images.githubusercontent.com/14130505/125196729-e0062380-e228-11eb-97bb-a6dcb390f208.png)

Nope, can't craft the hammer with modded stones. It doesn't handle it any better when trying to work with modded wood, either.

> there's no oredict in 1.16

This might be right but see the above, it's comparable since it's still the forge registry. Sorry if I'm using the wrong naming, I'm used to older versions where it really is called oredict.

> there's no version called "latest" (tetra, mgui, forge)

I literally downloaded the latest version of all three from CurseForge this afternoon. I think that's perfectly reasonable.

* tetra-1.16.5-3.11.1
* mgui-1.16.5-3.2.0
* Forge 36.1.31 for Minecraft 1.16.5

> required fields have been removed (crash log, steps to reproduce)

This is petty as fuck.

> "etc" is not a modlist

I'll concede on this point, but I was trying to give a relevant list because I know what mods Tetra isn't playing well with, and was expressing fluff as "etc".

Mods:
AdvancedRocketry-1.16.5-2.0.0-12-universal.jar
advgenerators-0.10.1.9-mc1.16.5.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
appliedenergistics2-8.3.1.jar
architectury-1.19.27-forge.jar
AutoRegLib-1.6-49.jar
bdlib-1.16.1.7-mc1.16.5.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
betterendforge-1.16.4-1.6.0.jar
BiomesOPlenty-1.16.5-13.1.0.471-universal.jar
Botania-1.16.5-416.jar
bwncr-1.16.4-3.9.16.jar
byg-1.2.9.jar
ChickenChunks-1.16.4-2.7.0.85-universal.jar
CodeChickenLib-1.16.4-3.5.1.408-universal.jar
cofh_core-1.16.4-1.2.1.jar
CookingForBlockheads_1.16.5-9.3.2.jar
create-mc1.16.5_v0.3.1c.jar
curios-forge-1.16.5-4.0.5.2.jar
DungeonCrawl-1.16.3-2.2.4.jar
engineersdecor-1.16.4-1.1.13.jar
engineerstools-1.16.4-1.1.5.jar
FarmingForBlockheads_1.16.5-7.3.1.jar
FastLeafDecay-v25.jar
ftb-chunks-1605.2.3-build.75.jar
ftb-essentials-1604.1.0.13.jar
ftb-gui-library-1605.2.1.41-forge.jar
gravestone-1.16.5-1.0.4.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
ImmersiveEngineering-1.16.5-5.0.0-135.jar
ImmersivePetroleum-1.16.5-3.3.0-4.jar
immersiveposts-1.16.5-4.1.0.jar
JAOPCA-1.16.5-3.4.0.9.jar
jei-1.16.5-7.7.0.106.jar
jeiintegration_1.16.5-7.0.1.15.jar
JustEnoughResources-1.16.3-0.12.0.100.jar
LibVulpes-1.16.5-1.0.2-25-universal.jar
Mekanism-1.16.5-10.0.21.448.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
MekanismTools-1.16.5-10.0.21.448.jar
mgui-1.16.5-3.2.0.jar
NaturesCompass-1.16.5-1.9.0.jar
pamhc2crops-1.16.3-1.0.2.jar
pamhc2foodcore-1.16.3-1.0.2.jar
pamhc2foodextended-1.16.3-1.0.2.jar
pamhc2trees-1.16.3-1.0.1.jar
Patchouli-1.16.4-51.jar
Placebo-1.16.4-4.5.0.jar
Quark-r2.4-312.jar
ScalableCatsForce-2.13.5-build-2-with-library.jar
SereneSeasons-1.16.5-4.0.1.91-universal.jar
SpawnerFix-1.16.2-1.0.0.2.jar
StorageDrawers-1.16.3-8.2.2.jar
TerraForged-1.16.5-0.2.10.jar
tetra-1.16.5-3.11.1.jar
titanium-1.16.5-3.2.8.4-10.jar
Toast-Control-1.16.4-4.3.1.jar
TrackAPI-1.16.4-forge-1.2.1.jar
Transport-1.16.5-3.6.0.jar
UniversalModCore-1.16.4-forge-1.0.1.jar
WailaHarvestability-mc1.16.x-forge-1.1.15.jar
worldedit-mod-7.2.5-dist.jar
YungsApi-1.16.4-Forge-6.jar

**Comment by Caeleron** [comment] 2021-07-11 14:29
In addition, the recipe located at (https://github.com/mickelus/tetra/blob/master/src/main/resources/data/tetra/recipes/hammer_modular.json) seems to have no effect. Opening the .jar I received on CurseForge shows that it is in fact hard-coded to vanilla wood and stone despite the fact that support for generic wood and stone has been a feature since 1.12 (https://github.com/mickelus/tetra/commit/39f835e3)

Granted, I also find it concerning that all of the code you have on GitHub does not match what you are distributing.
