### ISSUE TITLE
[Bug] Enchanted items in tetra mod have excessive glint effects

### ISSUE THREAD

**Issue by Larun1517** [mickelus/tetra#576] opened 2022-02-16 15:20 UTC
### Observed behaviour

Enchanted items in tetra mod have excessive glint effects.

![2022_2_17_46](https://user-images.githubusercontent.com/88703314/154292820-8eb32f05-c703-443d-a7ea-f5040698eb36.gif)
netherite sword, wooden sword and stone axe
left - vanilla, right - tetra

Whether you try to enchant first or try to modify it first, the results are the same.

*Sorry for my short english. I borrowed the some help of a translator.

### Expected behaviour

Glint effects are adjusted to the same level.

### Steps to reproduce

Just try to enchant to the tools or weapons.

### Tetra version

4.5.0

### mutil/mGui version

4.2.0

### Forge version

1.18.1 - 39.0.76

### Other mods

none.

**Comment by mickelus** [comment] 2022-02-17 11:47
Duplicate of #469, closing.

**Closed as completed by mickelus** 2022-02-17 11:47 UTC
Labels: bug
