### ISSUE TITLE
Belt upgrades for more integrity (-> more belt slots)

### ISSUE THREAD

**Issue by TheGrinchOnMath** [mickelus/tetra#853] opened 2024-10-28 10:59 UTC
### Feature description

More expensive belt upgrades:
add more integrity, to be able to use the maximum amount of iron loops, and therefore be able to carry more tools.

Example: 
- before the shulker upgrade, add an ender eye upgrade (using multiple eyes) that add 1-2 integrity slots.
- after shulker shell upgrade, add netherite reinforcement upgrade (adds 2-4integrity, uses up a smithing template and several netherite ingots)
- nether star / dragon egg: add 3-4 integrity, possible final "vanilla upgrade"

### How it improves the player experience

Especially in big packs, tools tend to accumulate, sometimes even filling half of the player inventory. the toolbelt provides a solution to this, however the capacity I have been able to reach (12 slots) has so far proven to be quite insufficient, especially mid-endgame kitchen sink packs. 

Clearing up the inventory by storing tools in the toolbelt leaves the tools easily accessible and clears up the player inventory, reducing sorting hassles and worries of a constantly full inventory

### Tetra synergies

Letting the player carry more tools without cluttering the inventory enables the player to carry other things, giving more time for creation and exploration, and increases the usefulness of the toolbelt in the later game when a lot of tools are frequently needed.

**Comment by mickelus** [comment] 2024-10-28 20:32
The current maximum integrity for belts is as intended. If a pack adds a large amount of tools that the players needs to have access to that pack can expand on the available quick access slots. Closing.

**Closed as completed by mickelus** 2024-10-28 20:32 UTC
