### ISSUE TITLE
[Bug] tetra weapons drastically reduce fps

### ISSUE THREAD

**Issue by SeanChengN** [mickelus/tetra#624] opened 2022-06-01 03:57 UTC
### Observed behaviour

Holding a tetra weapon in your hand or in your inventory will drastically reduce fps.

I did two experiments, as shown below:
[1] Clean client
![tetra-5](https://user-images.githubusercontent.com/20624068/171322413-6fbac207-e42a-452e-a653-619c113ec5b6.gif)
FPS Changed: 525 → 465 → 445 → 475 → 530 (drop 85)

[2] My modpack
![tetra-6](https://user-images.githubusercontent.com/20624068/171324280-7106c639-ac6e-406c-9f47-f40e118099b2.gif)
FPS Changed: 160 → 80 → 28 → 80 → 165 (drop 137)

### Expected behaviour

No fps drop

### Steps to reproduce

1. Modify parts at will.
2. Put weapons in your hand or in a chest or inventory.
3. Check the fps.

### Tetra version

tetra-1.18.2-4.9.1

### mutil/mGui version

mutil-1.18.2-4.5.0

### Forge version

1.18.2-40.1.25

### Other mods

FpsReducer2-forge-1.18.2-2.0 (To show fps)

**Comment by Dr-WeiAL** [comment] 2022-06-02 17:26
Yes, I also found this problem

**Comment by SeanChengN** [comment] 2022-06-03 02:41
tetra-1.18.2-4.9.2 still the same.

**Comment by mickelus** [comment] 2022-06-09 14:32
I'm unable to reproduce this issue.

**Comment by SeanChengN** [comment] 2022-06-10 03:48
> I'm unable to reproduce this issue.

More details: 
Turn off vertical sync, the maximum frame rate is unlimited, others keep the default.
![tetra-7](https://user-images.githubusercontent.com/20624068/172986381-a0c694bd-2618-4874-bab8-20bee633118f.gif)

In order to rule out the problem of fps display, I replaced it with FPS-Monitor-1.18.2-1.2.1, the issue remains.

**Comment by Dr-WeiAL** [comment] 2022-06-15 02:08
Whether it's a drop, inventory, or handheld, as long as you can see the item, the fps will decrease

**Comment by Dr-WeiAL** [comment] 2022-06-15 10:23
> I'm unable to reproduce this issue.

@mickelus Try installing rubidium?
After testing, I found that holding the item after installing rubidium will cause the fps to drop
But installing optifine doesn't cause fps drop

**Comment by Yizhouuu** [comment] 2022-08-04 04:42
me too

**Comment by Yizhouuu** [comment] 2022-08-04 04:44
the fps reducing changes with the weapons, and i found this reduces the most
![)4B8Q5(1_D`X{9TXPSBI@OA](https://user-images.githubusercontent.com/107225762/182764976-c803340a-de4a-4090-96dc-b1b718f3cc18.png)

**Comment by Hahahavana** [comment] 2022-08-25 05:29
Can confirm there's a severe issue possibly in conjunction with Rubidium. With tetra installed it was causing constant low-level stuttering, particularly while holding a weapon or tool from the mod, and even caused certain other mods to start stuttering in certain situations. Uninstalling tetra stopped all performance problems I had.

**Comment by SeanChengN** [comment] 2022-08-25 06:49
> Can confirm there's a severe issue possibly in conjunction with Rubidium. With tetra installed it was causing constant low-level stuttering, particularly while holding a weapon or tool from the mod, and even caused certain other mods to start stuttering in certain situations. Uninstalling tetra stopped all performance problems I had.

This error can be reproduced without Rubidium.

**Comment by Dr-WeiAL** [comment] 2022-08-25 14:42
I don't know why, I don't have this problem recently

**Comment by ChuijkYahus** [comment] 2022-08-29 13:24
Have encountered this problem too.
Was tested with Rubidium, Rubidium Extra, Rubidium Dynamic Lights, Starlight. All mods are latest.
Tetra's enchantment glitters are OFF.

On personal test kitchen sink(333 mods) in barren superflat:
Rendering a few unimproved items(only tetra's materials & module types, same below) causes fps drop from 230 to around 50
Rendering a whole chest of somewhat improved items causes fps drop to 7
Rendering one item with many improvements causes fps drop to around 35

Without Rubidium, fps drop still exists, but not that severe as mentioned above.

**Comment by Dr-WeiAL** [comment] 2022-09-13 16:34
I seem to have found the problem
This problem is caused by startup java arguments
This problem does not occur when you start the game without any java arguments
I think those of us with problems can try removing the java arguments and try again
For example me, the java arguments I use is this one below
`-XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Dfml.ignoreInvalidMinecraftCertificates=True -Dfml.ignorePatchDiscrepancies=True -Dlog4j2.formatMsgNoLookups=true`

**Comment by Dr-WeiAL** [comment] 2022-09-27 01:18
> 

By the way, when I use the HMCL launcher, even if I don't add java arguments, the frame rate will be reduced, and adding java arguments when using the PolyMC launcher will reduce the frame rate.

**Comment by Dr-WeiAL** [comment] 2022-09-27 01:19
> I seem to have found the problem This problem is caused by startup java arguments This problem does not occur when you start the game without any java arguments I think those of us with problems can try removing the java arguments and try again For example me, the java arguments I use is this one below `-XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Dfml.ignoreInvalidMinecraftCertificates=True -Dfml.ignorePatchDiscrepancies=True -Dlog4j2.formatMsgNoLookups=true`

Incidentally, I can add that even if I don't add java arguments when using the HMCL launcher, the frame rate will be reduced, but only when I add java arguments when using the PolyMC launcher.

**Comment by Dr-WeiAL** [comment] 2022-09-27 01:25
> > I seem to have found the problem This problem is caused by startup java arguments This problem does not occur when you start the game without any java arguments I think those of us with problems can try removing the java arguments and try again For example me, the java arguments I use is this one below `-XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Dfml.ignoreInvalidMinecraftCertificates=True -Dfml.ignorePatchDiscrepancies=True -Dlog4j2.formatMsgNoLookups=true`
> 
> Incidentally, I can add that even if I don't add java arguments when using the HMCL launcher, the frame rate will be reduced, but only when I add java arguments when using the PolyMC launcher.

I think this should be the problem, please ask the author has time to test it?
@mickelus 
There are two cases and the test conditions are described below:
1. Use HMCL launcher, install rubidium, and then you will have this problem
2. Use PolyMC launcher, install rubidium, add the java arguments as described above, and then you will get this problem

**Comment by mickelus** [comment] 2023-02-28 00:00
Closing, scrapped the item renderer.

**Closed as completed by mickelus** 2023-02-28 00:00 UTC
Labels: bug, Needs refinement
