### ISSUE TITLE
tetra:feature should be a structure

### ISSUE THREAD

**Issue by Fabizocker456** [mickelus/tetra#470] opened 2021-07-21 18:03 UTC
### Feature description

The Tetra-structure (tetra:feature) should be a structure. Not only does this allow certain functionalities (/locate and structure commands from other mods), it also makes sense (It is described as a **structure** deep underground in cold biomes) and aligns with vanilla mechanics (Anything that isn't super common like trees and boulders or natural is a structure, especially man/ancestor/etc. made builds). It also doesn't limit functionality. Please correct me if I'm wrong

### How it improves the player experience

It only makes sense, and allows structure compasses from other mods to work with tetra:features.

### Tetra synergies

It only makes sense, and would be helpful, especially since tetra is data-driven.

**Comment by Fabizocker456** [comment] 2021-07-21 18:04
Oh, and the name could be changed ;)

**Comment by mickelus** [comment] 2021-07-21 20:51
Your description doesn't make sense, but I'm assuming this is a duplicate of #156. Closing.

**Closed by mickelus** 2021-07-21 20:51 UTC

**Comment by Fabizocker456** [comment] 2021-07-21 21:00
It isn't. I'm just proposing a technical change: The forge should (worldgen-wise) be a structure, not a feature. This wouldn't affect gameplay directly, but allow /locate and (configurable) structure compasses from other mods to locate them. It eould also make sense because all vanilla buildings are structures, and only things like boulders are features.

**Comment by StrangerSon71** [comment] 2021-07-23 21:17
Please reopen this @mickelus it isn’t a duplicate

**Comment by mickelus** [comment] 2021-07-24 13:33
The technical solution is the same, you can subscribe to that issue if you want to be notified when it's resolved.
