### ISSUE TITLE
Crash in holograph UI

### ISSUE THREAD

**Issue by Darkhax** [mickelus/tetra#209] opened 2020-08-12 07:17 UTC
## Bug Report

**Observed Behaviour**
I opened the holograph, clicked something, and it crashed.

Crash log: 
https://gist.github.com/Darkhax/a69475e8da7f8155f924d743ee8cde9a starts at line 4603

**Expected Behaviour**
No crash

**Minimal setup needed to reproduce**

- Forge version: 32.0.108
- Tetra version: 3.0.0-pre.6
- Tetra configuration: 
- Other mods: It's the FC config

**Steps to reproduce**
I opened the holosphere and clicked on one of the tool part buttons. Maybe I clicked too fast or something.

**Comment by mickelus** [comment] 2020-08-12 16:09
I've heard of this before but they've never provided a log and I've never been able to reproduce it, so thanks a bunch!
I've been clicking around frantically and I still can't reproduce it, is it one of these buttons that you clicked?
![button](https://user-images.githubusercontent.com/224698/90039505-fdeca080-dcc6-11ea-93ff-d3d4932a8983.png)

**Comment by Darkhax** [comment] 2020-08-13 01:21
I think I was on the main page, so like toolbelts and blades.

**Comment by Darkhax** [comment] 2020-08-14 00:51
This seems to be the same issue but with the repair gui specifically. https://gist.github.com/Darkhax/248fa8fd3d953b8681b53ac977ad1acd

**Comment by joshgreenwell** [comment] 2020-09-06 20:20
Hey, I ran into this issue today.

My actions leading up to it involved:
1. Opened GUI
2. Click Shields icon
3. Viewed plates
4. Click breadcrumb back to shields
5. Clicked Items breadcrumb immediately after
5. Crash

Prior to that, I had been jumping around the holo GUI a lot.
That being said, I can't reproduce it.

[crash-2020-09-06_15.08.21-client.txt](https://github.com/mickelus/tetra/files/5180231/crash-2020-09-06_15.08.21-client.txt)

**Comment by TBiscuit1** [comment] 2020-11-11 17:46
Well, I might have found the bug? I spammed "q" and one of the icon and it lead me to a page with all the different type (without the option to go back and the Craft>>???>>??? beeing invisible) and when I click on one of the type, it crashed

**Comment by mickelus** [comment] 2020-12-25 13:54
This should have been fixed in one of the releases for 1.16, or at least I'm no longer able to reproduce it by clicking around frantically.

**Closed by mickelus** 2020-12-25 13:54 UTC
Labels: bug
