### ISSUE TITLE
Treatises Not Working Tetra 1.19.2-5.2.1

### ISSUE THREAD

**Issue by Pelkel** [mickelus/tetra#719] opened 2023-05-14 00:16 UTC
### Observed behaviour

Treatises for things like Metal and Gemstones do not appear to add any extra benefit to crafted weapons or tools, despite their tooltip info suggesting otherwise.  

### Expected behaviour

Treatises should be applying some sort of benefit to a given weapon or tool for being within the 5x5x5 crafting area.

### Steps to reproduce

1. Place down workbench or forgebench
2. Work with a weapon or tool of some kind to see parameter changes
3. Obtain Treatise, either from creative or from villager trades (ex: Metal Expertise from a toolsmith)
4. Place down the treatises within the 5x5x5 area
5. Work with the same weapon or tool with the same items to see no effective changes being shown or recorded
![2023-05-13_18 26 45](https://github.com/mickelus/tetra/assets/76638300/fbf5d987-0abd-4575-9bda-027dbee71d57)
![2023-05-13_18 27 26](https://github.com/mickelus/tetra/assets/76638300/9142679c-a846-4dd0-92e6-87445a4a50d1)

The two screenshots show attempts at working with metal, one with the metal expertise and one without, no increase in stats are shown with metal expertise despite the tooltip saying that something should happen to either damage or durability.  Provided a screenshot of the info that comes up for the scroll item.
![Treatise Info](https://github.com/mickelus/tetra/assets/76638300/f3254483-59a1-427f-8905-4abb7d334a53)
![2023-05-15_01 11 27](https://github.com/mickelus/tetra/assets/76638300/8d44ea13-8a2f-47f2-afe6-720ef787c95b)

### Tetra version

6.2.1

### mutil/mGui version

5.1.0

### Forge version

1.19.2 43.2.8

### Other mods

Botania
Ars Nouveau
Ars Armiger

**Comment by mickelus** [comment] 2023-05-14 12:12
Unable to reproduce this. It's not possible to say what's causing this for you as you've skipped filling out the "Other mods" field but it's apparent you've got several other mods set up in your instance. Closing, provide the minimal set of mods required to reproduce this, the mean to acquire the treatise and the nbt of the treatise and we can look into reopening this.

**Closed as completed by mickelus** 2023-05-14 12:12 UTC
Labels: bug

**Comment by Pelkel** [comment] 2023-05-14 12:40
Updated, provided a screenshot of what I assume is the NBT info as I don't actually know how to get you that info specifically.  I will note, I did not notice any upgrades even when using Netherite, a vanilla minecraft material.  I would like to also note that it seems forge stabilizers and the treatises do not stack. Is this by design?

**Comment by mickelus** [comment] 2023-05-15 20:09
Are you unable to reproduce the issue without those mods? Does the issue occur both with the treatise from the creative inventory and the traded one? You note that the treatise doesn't stack with the forge hammer stabilizer buff, how is that noticeable if it's not working at all?

**Comment by Pelkel** [comment] 2023-05-17 01:47
I ran tests in a second profile that had only Tetra.  In that world, this is everything I found, using a diamond sword and netherite ingots as the baseline on a blade.
Metal Treatise seems to work when from creative menu, I think.  When I have it and nothing else down with the forge I notice an extra increase of .40
I am unable to tell you if a traded one works because every single villager I trade with rolls only the Hammer Treatise for some reason
Two Stabilizers slotted into the forge appears to give an increase of .80, but having both the stabilizers AND the treatise causes only a .40 increase, which seems to suggest the treatise is overwriting the forge?


If I'm honest, it's really hard to tell whether something is or isn't working in your mod because none of the extra bonuses are actually marked in any way as to what values they provide.  Your tooltips give some description of what should happen but without knowledge of what should actually change and by how much, it's very difficult confirming such things have actually occurred.  I don't even know what is or is not intended in order to give any further info.

Edit: Conflict is with Origins: Classes (Forge), which I thought I had marked up above.  The .40 disappears only when that mod is active in my tests.

**Comment by crafting-Aaron** [comment] 2023-07-18 08:58
I am also having issues with Origins: Classes (Forge) where the new Tetra version 5.3.1 even crashes with it #735 (Holy moly you dealt with that many issues mickelus) that mentions the workbench on the log.

Anyway, bonuses do not also apply in my experience.
When using 5.3.0, using Wood Expertise for example, will not provide bonus dmg to a crossbow or bow with a maple plank. There is no difference when adding or removing the scroll. It is placed 2 blocks above like specified and next to working scrolls such as Howling Blade,

Seems like the workbench overall is having a conflict for some reason with Origins: Classes.
