### ISSUE TITLE
[1.12.2] GUI being buggy after a single tool modification

### ISSUE THREAD

**Issue by Cynosphere** [mickelus/tetra#107] opened 2020-02-06 00:03 UTC
## Bug Report

**Observed Behaviour**
Shows part dialog for a split second when clicking on a part and cannot be interacted with afterwards until re-opening the GUI which it then will just happen again trying to click on a part.
![Demonstration](https://totallynotavir.us/i/fbj90oii.gif)

**Expected Behaviour**
Being able to interact with the part dialog normally and it staying

**Minimal setup needed to reproduce**
- Forge version: 1.12.2- 14.23.5.2847
- Tetra version: 0.39.1
- Tetra configuration: Unmodified from default
- Other mods: https://gist.github.com/Cynosphere/2c87d8b4034e95e8418369290c2a0769

**Steps to reproduce**
- Obtain a vanilla tool
- Put it in the table
- Modify a part
- Attempt to modify another part (same or different)

**Comment by mickelus** [comment] 2020-02-06 18:28
I'm unable to reproduce this in a setup with only tetra. Is that the minimal mod setup required for this issue occur?

**Comment by Cynosphere** [comment] 2020-02-06 19:27
I guess so

**Comment by mickelus** [comment] 2020-02-06 19:55
That's alot of stuff to set up properly by hand :s. You're not running a modpack by any chance?

**Comment by Cynosphere** [comment] 2020-02-06 23:40
I am, but I don't know how legally I can distribute it as its just a MultiMC export since I don't really use Twitch's client to make/play packs.

**Comment by scribbler957** [comment] 2020-03-06 06:43
I've had this problem too. I've noticed that it seems to cause recipes to mangle. I'll look into reproducing it.

**Comment by scribbler957** [comment] 2020-03-06 07:48
I think I've narrowed it down to Dark Roleplay Core/Dark Roleplay Medieval. Although, other mods could cause similar interactions.
@Cynosphere are either of these in your modpack?

**Comment by scribbler957** [comment] 2020-03-06 08:33
Nevermind. The gif wasn't playing right before. I think my issue is related, but separate. I'll open a new issue.

**Comment by mickelus** [comment] 2020-07-03 00:07
Closing this as it still has not been refined, feel free to reopen if you manage to provided the requested information.

**Closed by mickelus** 2020-07-03 00:07 UTC
Labels: Needs refinement
