### ISSUE TITLE
[Bug] Unable to scroll through the displayed items in Holosphere

### ISSUE THREAD

**Issue by TDCMC** [mickelus/tetra#627] opened 2022-06-09 09:37 UTC
### Observed behaviour

![Screenshot from 2022-06-09 13-35-45](https://user-images.githubusercontent.com/69730881/172814832-adb4234f-fee6-485d-b62f-cbe61bd5ffee.png)
I didn't check other tabs but in the materials tab, I noticed that when there are more items than what would fit on the screen, there isn't a scollbar to scroll through the items.

### Expected behaviour

To be able to scroll through the displayed items.

### Steps to reproduce

1. Open the Holosphere
2. Select (as an example) Materials
3. If the amount of displayed items exceeds what would fit in the screen, some information is inaccessible. (I'm using Grimoire of Tetra for mod compats)

### Tetra version

4.9.2

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.47

**Comment by mickelus** [comment] 2022-06-09 14:31
Closing, duplicate of #423.

**Closed as completed by mickelus** 2022-06-09 14:31 UTC
Labels: bug
