### ISSUE TITLE
Tetra Bow does not draw from quiver

### ISSUE THREAD

**Issue by Rarket-glitch** [mickelus/tetra#247] opened 2020-11-18 00:48 UTC
## Bug Report

**Observed Behaviour**
When using a tetra bow, the bow does not draw from the toolbelt quiver

Crash log: 

**Expected Behaviour**
An arrow should be drawn from the toolbelt to my off hand and used with the bow

**Minimal setup needed to reproduce**
Toolbelt: 
3 iron loops
Mesh quiver + quick latch
Leather belt

Bow: 
basic string + unbreaking 3, punch 2
Makeshift long stave + power 5
Iron stabilizer

- Forge version: 34.1.42
- Tetra version: 1.16.4
- Tetra configuration: 
- Other mods:

**Steps to reproduce**
use bow with no arrows in inventory, only in quiver (have to be in survival <<<)

**Comment by puppydemon20** [comment] 2020-11-18 01:30
Something to note, the belt will allow infinity to work on Tetra Bows.

**Comment by alphaNumeric01** [comment] 2020-11-22 08:10
I'm getting this issue as well. So far, the only kind of bow that the latch appears to work as intended with is the vanilla default bow. It doesn't seem to work with ANY of the tetra bows.

**Comment by mickelus** [comment] 2020-12-25 13:28
Fixed in 3.4.0!

**Closed by mickelus** 2020-12-25 13:28 UTC
