### ISSUE TITLE
can't see the icons for opening crates with shaders

### ISSUE THREAD

**Issue by UwUsheep** [mickelus/tetra#582] opened 2022-02-27 23:28 UTC
### Observed behaviour

So I was In one of the structures and was about to open the crate but the shaders made a white screen instead of the hammer Icon, Im using 1.16.5 latest release

### Expected behaviour

I expected the mod to have compatibility with shadersI am using project LUMA

### Steps to reproduce

1. have shaders and look for a underground structure
2. find a crate or chest and hover over the icons.
3. The Icons are white

### Crashlog

no crash

### Tetra version

3.20.0

### mutil/mGui version

3.3.0

### Forge version

1.16.5 36.2.28

### Other mods

I only have this and optifine on

**Comment by mickelus** [comment] 2022-02-27 23:48
Closing, duplicate of #371.

**Closed as completed by mickelus** 2022-02-27 23:48 UTC
Labels: bug
