### ISSUE TITLE
[1.15.2] Placing an item in a workbench or rack does not render that item for other players on server

### ISSUE THREAD

**Issue by IceDragon200** [mickelus/tetra#213] opened 2020-09-13 15:40 UTC
## Bug Report

**Observed Behaviour**

When an item is placed in a workbench or on a rack, the placing player is able to see the item's physical representation in the world, however other players do not see the item until they interact with the block holding the item.

Crash log: No crash, just visual issue

**Expected Behaviour**

Adding or removing an item from Tetra blocks should notify all players of it's state change.

**Minimal setup needed to reproduce**

- Local Multiplayer (could work over normal MP too, but only tested with local) with at least 2 players
- Forge version: 1.15.2 - 31.2.36
- Tetra version: e.g. 2.18.1
- Tetra configuration: Unchanged from vanilla
- Other mods: 
* Inventory Sorter
* No other noteworthy mods

Optifine or any other performance related mods are not present

**Steps to reproduce**

- Place a tool into a workbench and then close the ui, have the other player look at the bench (not open the UI), the item is not shown to be on the bench until they interact with it.

**Comment by mickelus** [comment] 2020-12-25 13:54
Can you check if you are you able to reproduce this in the latest verions?

**Comment by IceDragon200** [comment] 2020-12-25 14:50
Latest 1.15 release, or latest 1.16 release?

Last time I checked the 1.16 release had the same issue, I'll try the 1.15 one tomorrow at latest and let you know

**Comment by mickelus** [comment] 2020-12-25 17:09
1.16, I've not updated 1.15 since before this issue afaik.

**Comment by IceDragon200** [comment] 2020-12-27 21:27
@mickelus Haven't been feeling well this weekend, so I'll let you know if it's fixed next week possibly

**Comment by mickelus** [comment] 2020-12-27 22:29
No stress, take care of yourself!

**Comment by ocram9** [comment] 2020-12-29 18:42
Can confirm this is happening on 1.16 too. Playing on the latest 3.4.0 build. Although for us it's the other way around. Placing it is fine but once removed the other player sees the item on the workbench until they interact with it.

**Comment by mickelus** [comment] 2021-01-03 23:02
I got it wrong about not being able to boot up local multiplayer in my dev environment, fixed in 3.5.0!

**Closed by mickelus** 2021-01-03 23:02 UTC
Labels: bug
