### ISSUE TITLE
Crash during load

### ISSUE THREAD

**Issue by Corvus20** [mickelus/tetra#365] opened 2021-02-24 16:39 UTC
## Bug Report

**Observed Behaviour**
Game is launched, loads for a bit, and then crashes, and the crash report mentions a tetra invalid modular sword. Also proceeds to mention a few other mod's transformers such as BetterEndForge, AbnormalsCore, Apotheosis, Charm, and Outer End, apparently tying to the tetra error in some way.

**Crash Log**:
https://gist.github.com/mickelus/25f7b32dd24021f51f4dc3d832adf7bf

**Expected Behaviour**
This kind of goes without saying, but I wouldn't expect it to crash while loading.

**Minimal setup needed to reproduce**

- Forge version: 1.16.5, 36.0.42
- Tetra version: 3.6.1
- Tetra configuration: Default configuration, haven't tweaked any config files.
- Other mods: The important one to mention aside from the ones I mentioned earlier is Tetranomicon, a material compatibility bundle addon mod for tetra, I'm using the latest build of that, too. I have other mods installed, but they don't seem to have any role in this issue.

**Steps to reproduce**

1. Install the aforementioned mods latest builds and the build of forge.
2. launch the game
3. wait for a minute or so for the game to error while loading
4. crash with error involving an invalid modular sword.

This could be the issue of another mod's enchantment or something, but figured you should at least know being tetra is involved.

Update: As of 3/3/2021, this issue persists with the latest available public builds of tetra, mgui, and forge 1.16.5 36.0.44

**Comment by copygirl** [comment] 2021-02-24 16:49
Duplicate of #359. You can downgrade to Forge `36.0.40` for now to fix this issue.

**Comment by IamStig** [comment] 2021-02-24 22:14
For clarity Tetra 3.6.1 crashes on load on Forge 36.0.41 & 36.0.42. Only known fix is downgrading Forge to 36.0.40. Also this may not be compatible solution with some mods ...RFTools Dimensions 7.0.2 beta for instance requires forge 36.0.42+

**Comment by benbenlaw** [comment] 2021-02-25 17:10
also crashes on forge 36.0.43

**Comment by F0x06** [comment] 2021-02-25 18:09
Hi, any idea/eta for a fix @mickelus ? I tried to find a fix myself without success, i'm not really experienced with forge modding.

Currently this block updates on my modpack because i'm using both RFTools Dimensions and Tetra and i'm stuck at forge 36.0.39

Thanks :)

**Comment by F0x06** [comment] 2021-03-01 10:16
@mickelus Just noticed that the sources are outdated on this git repo, i can't help or make a PR, are you planning to push the latest sources for beta `tetra-1.16.4-3.6.1` ? Thanks.

**Comment by AbdulMuqsit** [comment] 2021-03-02 00:09
+1 to pushing the latest source so we can look into the issue, thank you

**Comment by Gbergz** [comment] 2021-03-02 08:53
Same crashing(& same crashreport) issue when joining world on **Forge 36.0.25** & **Tetra-3.6.1**.

**Comment by arBorghi** [comment] 2021-03-02 22:46
Yep, same crash while trying to launch the game. I'm using **Forge 36.0.43** & **Tetra 3.6.1**
[crash-2021-03-02_19.39.27-client (Tetra mod).txt](https://github.com/mickelus/tetra/files/6072248/crash-2021-03-02_19.39.27-client.Tetra.mod.txt)

**Comment by BLSK** [comment] 2021-03-03 07:55
yeah a new version is needed... many mods (around 150) that I use can't support below 36.0.42 anymore... just figured I would throw that out there... do with it what you do.  Hope it gets updated soon enough :) but no rush

**Comment by dromedar17** [comment] 2021-03-03 21:40
same problem on forge 36.0.44, related to INVALID-tetra:modular_double
[crash-2021-03-03_22.34.33-client.txt](https://github.com/mickelus/tetra/files/6079352/crash-2021-03-03_22.34.33-client.txt)

**Comment by mickelus** [comment] 2021-03-04 03:46
Fixed in 3.7.0

**Closed by mickelus** 2021-03-04 03:46 UTC
Labels: bug
