### ISSUE TITLE
World Gen Crash, using Terraforged Worldgen.

### ISSUE THREAD

**Issue by Corvus20** [mickelus/tetra#325] opened 2021-01-21 19:40 UTC
## Bug Report

**Observed Behaviour**
Was exploring the world, and the game just hard crashed. No "not responding" or stuttering. Crashlog indicates something was wrong with "tetra:feature". 

Crash log:
[crash-2021-01-21_14.31.01-client.txt](https://github.com/mickelus/tetra/files/5851684/crash-2021-01-21_14.31.01-client.txt)

**Expected Behaviour**
I expected Tetra to not crash the game when trying to generate whatever this "tetra:feature" is when using Terraforged.

**Minimal setup needed to reproduce**

- Forge version: 1.16.4 35.1.36
- Tetra version: 3.5.3
- Tetra configuration: configuration files have not been modified.
- Other mods: TerraForged-1.16.4-0.2.0-BETA-8

**Steps to reproduce**
Create a terraforged world, wander around a while. Eventually the game will try to generate "tetra:feature" and crash.

**Comment by Corvus20** [comment] 2021-01-21 21:36
Update: Upon looking at the crash log further, Subterranean wilderness seems to be involved. Eidolon has been experiencing an issue with subterranean wilderness, and being that these both involve underground structure, this may well be an issue on subterranean wilderness' end, but I cannot draw any conclusions. I would recommend checking out the issue on SubWild's issue tracker to see if it is the same problem.

**Comment by mickelus** [comment] 2021-01-21 22:31
This is indeed due to subterranean wilderness, please list all other mods in the future.

Closing, this is a duplicate of #316.

**Closed by mickelus** 2021-01-21 22:31 UTC
