### ISSUE TITLE
Glitched item [Bug] 

### ISSUE THREAD

**Issue by Thebomb2d** [mickelus/tetra#785] opened 2023-12-17 22:52 UTC
### Observed behaviour

I had misplaced my holosphere. I decided to use /give to get another one. While doing this I couldn't find the holosphere item. I instead found an item called "Holo". Curious, I gave it to myself. Right clicking worked the same as the holosphere, but shift right clicking on the ground crashed the game and took my world with it. I forgot to get the crash log before deleting that instance of Minecraft

### Expected behaviour

I should have gotten a functional holosphere, not a glitched one.

### Steps to reproduce

Use /give playerName tetra:holo
Shift right click on ground

### Tetra version

6.1.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1 47.2.0

**Comment by mickelus** [comment] 2023-12-22 10:03
It's intended behavior that giving yourself a modular item without modules, gets you a modular item without modules. Closing.

**Closed as completed by mickelus** 2023-12-22 10:03 UTC
Labels: bug
