### ISSUE TITLE
Hammer Not Breaking Forge Crates and Blocks

### ISSUE THREAD

**Issue by Shrilll** [mickelus/tetra#288] opened 2021-01-02 19:05 UTC
## Bug Report

**Observed Behaviour**
I am using a blackstone T4 hammer and am not getting items when opening crates; however. the crowbar does work. I am also unable to mine forge blocks with a hammer

Crash log: n/a

**Expected Behaviour**
I expected for the hammer to work

**Minimal setup needed to reproduce**

- Forge version: forge 35.1.15
- Tetra version: tetra 3.4.0
- Tetra configuration: the default found in the direwolf 20 1.16 pack
- Other mods: see the direwolf20 1.16 modpack list

**Steps to reproduce**
I used a blackstone T4 hammer and attempted to mine forge blocks and break forge crates

**Comment by mickelus** [comment] 2021-01-03 23:00
Fixed in 3.5.0!

**Closed by mickelus** 2021-01-03 23:00 UTC

**Comment by zlepper** [comment] 2021-01-04 19:13
Just tested version 1.16.4-3.5.2. Still not working.

**Comment by zlepper** [comment] 2021-01-09 11:07
@mickelus Can you reopen this one?

**Comment by mickelus** [comment] 2021-01-09 21:44
I'm unable to reproduce it in 1.16.4-3.5.3 (although that should not have changed between .2 and .3), if you can provide me with a reproduction steps we should open it again!

**Comment by michmerr** [comment] 2021-01-10 22:13
To separate the two actions, is a T4 hammer supposed to be able harvest forge blocks? I wasn't able to until I leveled one to T6. (I'm still on 1.16.4-3.4.0, so can't comment on the current state.)

**Comment by zlepper** [comment] 2021-01-11 06:47
I was trying with a tier 4 (the double blackstone one), which is what I asked you need, since as far as I can see, you need the things from the forge caves to get higher tiers
