### ISSUE TITLE
Hammer Base on 1.12 doesn't show particles on reconfiguring to overcharged

### ISSUE THREAD

**Issue by Hate9** [mickelus/tetra#342] opened 2021-02-03 04:32 UTC
## Bug Report

**Observed Behaviour**
When the hammer base is configured to "overcharged", no particles appear.

**Expected Behaviour**
Enchantment particles appear when the hammer base is set to "overcharged" mode.

**Comment by mickelus** [comment] 2021-02-03 15:04
Closing, unable to reproduce this issue and you've remove that field from the template :). Not really supporting 1.12 anymore so there's no need to fix up your issue anyways!

**Closed by mickelus** 2021-02-03 15:04 UTC
