### ISSUE TITLE
[Bug] config setting to allow settling past settled I or II

### ISSUE THREAD

**Issue by Matom4** [mickelus/tetra#864] opened 2024-11-23 22:27 UTC
### Observed behaviour

Is there a config setting that allows me to change the settled cap limit

### Expected behaviour

read above

### Steps to reproduce

Which setting is it

### Tetra version

3.0.0

### mutil/mGui version

2

### Forge version

1.20.1

**Comment by mickelus** [comment] 2024-11-24 22:36
This is not a bug report, closing.

**Closed as completed by mickelus** 2024-11-24 22:36 UTC
Labels: bug
