### ISSUE TITLE
[Bug] Increasing durability breaks use progress so self-repairing effects don't work well in practice

### ISSUE THREAD

**Issue by stephen-smith** [mickelus/tetra#495] opened 2021-09-14 03:14 UTC
### Observed behaviour

When the durability of a tool changes, block breaking progress is reset.  This makes "Mana Repair III" render a tool almost entirely useless as it is constantly repairing and interrupting breaking progress.

### Expected behaviour

When the durability of a tool _increases_, block breaking progress is preserved.

### Steps to reproduce

1. Manasteel pick, Manasteel adze, Livingwood Handle (Leather wrap I), Mana string binding.
2. Full "Band of Mana" in Ring curio slot.
2. Ultimine 64 blocks; e.g. about half of the wood in a giant spruce.
3. Immediately try to break another block; e.g. another spruce log.
4. Progress is reset at ~88%; this repeats ~63 times, until the tool is at full durability again.

### Crashlog

[no crash]

### Tetra version

3.14.1

### mGui version

3.2.0

### Forge version

36.2.2

### Other mods

Enigmatica 6 modpack; lots of mods.  Others mentioned in the report:

* Botania 1.16.5-419
* FTB Ultimine 1605.3.0-build.25

**Comment by mickelus** [comment] 2021-09-14 21:50
Closing, duplicate of #310.

**Closed by mickelus** 2021-09-14 21:50 UTC
Labels: bug

**Comment by stephen-smith** [comment] 2021-09-14 23:03
Sorry about the dup. :(
