### ISSUE TITLE
Axes not stripping logs from other mods

### ISSUE THREAD

**Issue by NicholasRC7** [mickelus/tetra#144] opened 2020-04-07 01:09 UTC
## Bug Report

**Observed Behaviour**

When right-clicking axes on a log from another mod, nothing happens at all.
**Expected Behaviour**

When right-clicking axes on logs, they would turn into the stripped variant.
**Minimal setup needed to reproduce**

- Forge version: 1.14.4 - 28.2.3 
- Tetra version: 1.26.0  
- Tetra configuration: 
- Other mods: [Modlist](https://www.curseforge.com/minecraft/modpacks/kreation/relations/dependencies?)

**Steps to reproduce**

Make a tetra axe, such as an axe with two axe heads, an axe with a spike, or an axe with an adze.
Right-click on a log block that's not from vanilla

**Comment by mickelus** [comment] 2020-04-10 21:36
Is that the minimal set of mods required to reproduce this issue? I'm unable to reproduce this with just tetra.

**Comment by NillerMedDild** [comment] 2020-04-11 06:14
I'm also unable to reproduce this in Enigmatica 4

**Comment by Windspren** [comment] 2020-04-18 05:28
I can confirm that this happens with modded logs (tested with BoP's various logs and Autumnity's maple logs but otherwise axes work fine on vanilla logs

**Comment by mickelus** [comment] 2020-12-27 20:15
This should have been resolved in 3.0.0.

**Closed by mickelus** 2020-12-27 20:15 UTC
Labels: bug
