### ISSUE TITLE
Hammer not working all the time

### ISSUE THREAD

**Issue by LostMatter** [mickelus/tetra#216] opened 2020-10-11 16:22 UTC
## Bug Report

**Observed Behaviour**
sometimes when I have the right tier hammer, it says i don't have it. like "you need a tier 2 hammer to craft this, you have tier 2 available

**Expected Behaviour**
it to work

**Minimal setup needed to reproduce**

1.15 i don't know any of the other things of that.
- Other mods: i dont think its another mod thing.

**Steps to reproduce**
get a hammer and try. sometimes it works and sometimes it doesn't.

**Comment by mickelus** [comment] 2020-11-07 13:59
I'm unable to reproduce this and you are really unclear, closing.

Feel free to reopen if you're able to provide the steps required to reproduce this.

**Closed by mickelus** 2020-11-07 13:59 UTC
