### ISSUE TITLE
[Bug] Modular tools not working under very specific conditions

### ISSUE THREAD

**Issue by ThatBigDerp** [mickelus/tetra#732] opened 2023-07-15 20:07 UTC
### Observed behaviour

When I execute specific command that gives me modular tool with only handle and empty head slots, then go to table and get axe head or pickaxe head or any tool head, but leave the 2nd head slot empty and I go to break blocks the blocks drop nothing and become ghost blocks.

### Expected behaviour

Tool works as normal 2 headed modular tool.

### Steps to reproduce

1. Execute command: `/give @s tetra:modular_double{"double/handle":"double/basic_handle","double/basic_handle_material":"basic_handle/netherite"}
`
2. Go to workbench and get yourself any head BUT leave the 2nd slot empty.
3. Break block.

### Crashlog

NaN

### Tetra version

5.3.1

### mutil/mGui version

5.1.0

### Forge version

43.2.3

### Other mods

[✔] AI-Improvements-1.19.2-0.5.2
  [✔] AttributeFix-Forge-1.19.2-17.2.7
  [✔] attributetooltipfix-forge-1.19.2-1.0.0
  [✔] AutoRegLib-1.8.2-55
  [✔] autumnity-1.19.2-4.0.0
  [✔] BetterAnimationsCollection-v4.0.5-1.19.2-Forge
  [✔] bettercombat-forge-1.7.1+1.19
  [✔] BiomesOPlenty-1.19.2-17.1.2.544
  [✔] blueprint-1.19.2-6.1.2
  [✔] Boat-Item-View-Forge-1.19.x-0.0.4
  [✔] BoatBreakFix-Universal-1.0.11
  [✔] boatload-1.19.2-4.2.1
  [✔] BowInfinityFix-1.19.x-forge-2.5.1
  [✔] caelus-forge-1.19.2-3.0.0.6
  [✔] canary-mc1.19.2-0.2.7
  [✔] charmofundying-forge-6.2.1+1.19.2
  [✔] cloth-config-8.3.103-forge
  [✔] Clumps-forge-1.19.2-9.0.0+14
  [✔] CodeChickenLib-1.19.2-4.3.1.481-universal
  [✔] Compat-O-Plenty-1.19.2-2.0.1
  [✔] coroutil-1.19.2-1.2.37
  [✔] curios-forge-1.19.2-5.1.4.1
  [✔] CuriosQuarkOBP-1.19.2-1.2.3
  [✔] deuf-1.19.2-1.3
  [✔] dynamiclightsreforged-1.19.2_v1.4.0
  [✔] EasyAnvils-v4.0.11-1.19.2-Forge
  [✔] EasyMagic-v4.3.3-1.19.2-Forge
  [✔] eatinganimation-1.19-3.2.0
  [✔] Elytra aeronautics Forge-1.19.2-2.0.1
  [✔] ElytraPhysicsForge-1.1.1
  [✔] ElytraSwap-1.0
  [✔] embellishedenchanting-v1.3.4-1.19.2
  [✔] endertrigon-1.0
  [✔] Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0
  [✔] entity_model_features_forge_1.19.2-0.2.13
  [✔] entity_texture_features_forge_1.19.2-4.4.4
  [✔] everycomp-1.19.2-2.4.12
  [✔] ExperienceBugFix-1.19-1.41.2.3
  [✔] FarmersDelight-1.19.2-1.2.2
  [✔] FarmersRespite-1.19-2.0
  [✔] FastSuite-1.19.2-4.1.0
  [✔] firstperson-forge-2.2.3-mc1.19.2
  [✔] flywheel-forge-1.19.2-0.6.8.a
  [✔] forgery-3.3.3+1.19
  [✔] fusion-1.0.3-forge-mc1.19.2
  [✔] galosphere_delight_1.1.0_forge_1.19.2
  [✔] Galosphere-1.19.2-1.3.0-Forge
  [✔] gpumemleakfix-1.19.2-1.6
  [✔] guardvillagers-1.19.2-1.5.6
  [✔] illuminations-forge-1.19.2-1.10.9.20
  [✔] infernal-expansion-1.19.2-2.5.3
  [✔] InsaneLib-1.7.5-mc1.19.2
  [✔] jei-1.19.2-forge-11.6.0.1016
  [✔] JustEnoughResources-1.19.2-1.2.2.200
  [✔] lightspeed-1.19.2-1.0.5
  [✔] MaxHealthFix-Forge-1.19.2-8.0.1
  [✔] modelfix-1.8
  [✔] moonlight-1.19.2-2.2.43-forge
  [✔] mutil-1.19.2-5.1.0
  [✔] nocube's_farmers_compats_1.0.0_Forge_1.19.2
  [✔] notenoughanimations-forge-1.6.2-mc1.19.2
  [✔] oculus-flywheel-compat-1.19.2-0.2.1
  [✔] oculus-mc1.19.2-1.6.4
  [✔] origins-forge-1.19.2-1.7.1.0-all
  [✔] PacketFixerForge-1.1.3-1.19.2
  [✔] PassiveSkillTree-1.19.2-BETA-0.4.9a
  [✔] Placebo-1.19.2-7.3.0
  [✔] player-animation-lib-forge-1.0.2
  [✔] PresenceFootsteps-1.19.2-1.6.4.1-forge
  [✔] ProgressiveBosses-3.7.5-mc1.19.2
  [✔] PuzzlesLib-v4.4.3-1.19.2-Forge
  [✔] Quark-3.4-405
  [✔] QuarkOddities-1.18
  [✔] RealisticSleep-1.19.2-2.1.0.2-universal
  [✔] responsiveshields-2.2
  [✔] rottencreatures-forge-1.19.2-1.0.1
  [✔] rubidium_extras-1.19.2_v1.4.3
  [✔] rubidium-0.6.2b
  [✔] sereneseasonfix-1.19.2-1.0.8
  [✔] SereneSeasons-1.19.2-8.1.0.24
  [✔] smarterfarmers-1.19.2-1.7.1
  [✔] soundphysics-forge-1.19.2-1.0.18
  [✔] stackablefixes-1.19.2-1
  [✔] starlight-1.1.1+forge.cf5b10b
  [✔] Stoneworks-v4.0.1-1.19.2-Forge
  [✔] StorageDrawers-1.19-11.1.2
  [✔] swingthroughgrass-1.19.2-1.10.0
  [✔] TerraBlender-forge-1.19.2-2.0.1.166
  [✔] tetra-1.19.2-5.3.1
  [✔] tetrasdelight-1.19.2-1
  [✔] toofast-1.19-0.2.2.4
  [✔] translucencyfix-backport-2.1.0-forge
  [✔] Unique Enchantments Base-1.19.2-3.0.2.1
  [✔] Unique Enchantments-1.19.2-4.0.2.1
  [✔] UnusualEnd1.19.2_V1.4.3
  [✔] upgrade_aquatic-1.19.2-5.0.0
  [✔] v_slab_compat-1.19.2-1.4
  [✔] VariantCraftingTables-1.19.2-1.8.1
  [✔] VisualWorkbench-v4.2.4-1.19.2-Forge
  [✔] WaterWalkingFix-Forge-1.0.0
  [✔] whats-that-slot-forge-1.3.1+1.19.2
  [✔] YungsApi-1.19.2-Forge-3.8.9
  [✔] YungsBetterDesertTemples-1.19.2-Forge-2.2.2
  [✔] YungsBetterDungeons-1.19.2-Forge-3.2.2
  [✔] YungsBetterMineshafts-1.19.2-Forge-3.2.0
  [✔] YungsBetterNetherFortresses-1.19.2-Forge-1.0.5
  [✔] YungsBetterOceanMonuments-1.19.2-Forge-2.1.0
  [✔] YungsBetterStrongholds-1.19.2-Forge-3.2.0
  [✔] YungsBetterWitchHuts-1.19.2-Forge-2.1.0
  [✔] YungsExtras-1.19.2-Forge-3.1.0
  [✔] zombieawareness-1.19.2-1.12.3

**Comment by zinerith** [comment] 2023-07-16 07:22
So in other words, when you spawn an unobtainable item from the mod by using commands, said item doesn't work. No surprises there.

**Comment by mickelus** [comment] 2023-07-16 08:40
As zinerith noted, the observed behavior is in line with the intended behavior. I guess this could be converted into a feature request but as this is presented I can't see the value in that. Closing.

**Closed as not planned by mickelus** 2023-07-16 08:40 UTC
Labels: bug
