### ISSUE TITLE
[Bug] The Spear Bug in Apotheosis

### ISSUE THREAD

**Issue by CoolDemon96** [mickelus/tetra#697] opened 2023-02-11 21:54 UTC
### Observed behaviour

In the apotheosis fashion, it became possible to impose sharpness and prey on a trident and I wanted to test it on tetra spears, but I didn't succeed. 

### Expected behaviour

Tetra spears must take enchantments of sharpness, loot and capture.

### Steps to reproduce

1. Take a vanilla shovel and turn it into a spear. 
2. try to apply the enchantment listed above.

### Tetra version

1.19.2-5.0.1

### mutil/mGui version

1.19.2-5.1.0

### Forge version

1.19.2 - 43.2.4

### Other mods

Apotheosis-1.19.2-6.0.3.jar

**Comment by mickelus** [comment] 2023-02-25 22:51
Intended behavior, enchanting rules can be changed using tags. Closing.

**Closed as completed by mickelus** 2023-02-25 22:51 UTC
Labels: bug
