### ISSUE TITLE
Forged chest crash

### ISSUE THREAD

**Issue by Banh-Bao** [mickelus/tetra#350] opened 2021-02-06 17:05 UTC
https://pastebin.com/XiAap4M4

was trying to open the forged chest with hammer

**Comment by mickelus** [comment] 2021-02-07 20:34
Please update the issue so that it adheres to the template for bug reports. Probably a duplicate of #261.

**Comment by Banh-Bao** [comment] 2021-02-07 22:23
Ah yes it is the same is #261 my apologies for reissuing an already issued bug

**Closed** 2021-02-13 19:56 UTC
Labels: Needs refinement
