### ISSUE TITLE
[Bug] Sickle will not destroy foliage or plants

### ISSUE THREAD

**Issue by TheGecko26** [mickelus/tetra#550] opened 2022-01-12 01:03 UTC
### Observed behaviour

When using a sickle of any type on crops or plants, the sickle is unable to destroy said blocks and treats them as if you were mining bedrock. 

### Expected behaviour

I expected to destroy plants with the sickle

### Steps to reproduce

1. Place axe in workbench
2. Change axe head to sickle head of any variant
3. Attempt to harvest or destroy plant blocks 

### Tetra version

1.18.1- 4.3.0

### mGui version

1.18.1- 4.1.0

### Forge version

1.18.1 39.0.17

**Comment by mickelus** [comment] 2022-01-17 20:16
I'm unable to reproduce this. Note that the sickle works like the stonecutter in that it swings like a sword rather than holding down left-click to break blocks.

**Comment by TheGecko26** [comment] 2022-01-18 09:09
I went to verify my information was correct, and found that the sickle does harvest tree leaves and vines. The sickle however, cannot cut plants such as flowers, grass or ferns. To reiterate, this was done on version 4.3.0 of tetra, 4.1.0 of mutil on minecraft 1.18.1. The bug still occurs regardless of forge version from my experience so far.

**Comment by mickelus** [comment] 2022-01-18 20:13
The grass I broke sat on a moss block, so the moss block broke and the grass broke with it! Fixed in 4.4.0.

**Closed as completed by mickelus** 2022-01-18 20:13 UTC
Labels: bug, Needs refinement
