### ISSUE TITLE
Extreme offset when firing arrows at non cardinal directions 

### ISSUE THREAD

**Issue by MuteTiefling** [mickelus/tetra#394] opened 2021-04-12 17:30 UTC
## Bug Report

**Observed Behaviour**

Arrows don't go where shot. Best seen in the video below. 

https://streamable.com/lxxu98

**Expected Behaviour**

The arrow should be going roughly where I'm aiming, but it's consistently going towards ordinal directions if you're even a few degrees off of a cardinal

**Minimal setup needed to reproduce**

- Forge version:  1.16.5 36.1.0
- Tetra version:  tetra-1.16.5-3.8.0
- Tetra configuration: https://github.com/NillerMedDild/Enigmatica6/blob/master/config/tetra.toml
- Other mods: Enigmatica 6 mod pack

**Steps to reproduce**

Just shoot at any angle other than straight at the cardinal directions and you'll see this.

**Comment by MuteTiefling** [comment] 2021-04-12 17:35
I should note that a vanilla bow does not have this problem, nor any other modded bow.

**Comment by jjjet42** [comment] 2021-04-12 21:28
I have the same issue, it appears to be a visual bug. Very difficult to adjust my aim when I can't see where the arrow went. This is a duplicate of #270

**Comment by crafting-Aaron** [comment] 2021-04-16 06:20
Sadly seems to be an issue with Minecraft itself having a max rendered projectile velocity. To quote someone in a spigot forum:

> Velocity packets sent their X, Y and Z as a short which have a maximum value of 32767. Minecraft then divides this by 8000.0 to get a double value of velocity, which results in just under 4.1, giving a maximum visible velocity of 4.1. This means that any velocity over 4.1 gives incorrect positions and it will mess up the client.

> EDIT: Fun side note: Minecraft's terminal velocity (the max falling speed) is 3.92, which also is only a little bit under the maximum velocity.

Hopefully there is a way to modify this and raise the limit through a standalone mod but so far it does not seem like someone has done such a fix in recent game versions.

**Comment by mickelus** [comment] 2021-04-27 23:14
Fixed in 3.9.0

**Closed by mickelus** 2021-04-27 23:14 UTC
