### ISSUE TITLE
[Bug] Cannot modify bows to some extent

### ISSUE THREAD

**Issue by aWhisper20** [mickelus/tetra#532] opened 2021-12-25 06:57 UTC
### Observed behaviour

When attempting to make a type of bow other than the default shape (Recurve/Long), the item transforms into the correct shape for a split second, then promptly reverts to it's previous state. All inputted resources are refunded.
This occurs only for bow types. Things like risers and bindings can still be applied normally.

### Expected behaviour

Bow should transform into the requested shape instead of remaining as a straight bow.

### Steps to reproduce

1. place any type of bow in tetra workbench
2. select any type of bow other than straight (the default shape)
3. input materials
4. accept
5. ???
6. Not profit

### Tetra version

4.1.0

### mGui version

4.0.0

### Forge version

39.0.8

### Other mods

Tetra (by mickelus)
Simple Voice Chat (by henkelmax)
Sound Physics Remastered (by henkelmax)
Valhelsia Structures (by ValhelsiaTeam)
mutil (by mickelus)
Just Enough Items (JEI) (by mezz)
Flywheel (by jozufozu)
Falling Leaves (Forge) (by Cheaterpaul)
Create (by simibubi)
Repurposed Structures (Forge) (by telepathicgrunt)
Valhelsia Core (by ValhelsiaTeam)
Stay True (by haimcyfly)
Xaero's World Map (by xaero96)

All are most recent version for 1.18.1 as of 24th of december

**Comment by mickelus** [comment] 2021-12-27 23:04
I'm unable to reproduce this.

**Comment by aWhisper20** [comment] 2021-12-27 23:57
> I'm unable to reproduce this.

I'll upload a video as soon as I'm able. 
For now, this is the curseforge launcher modpack I'm using where the problem is occurring.
https://www.dropbox.com/s/pftl8kegtu05zs8/Year%20End%202021.zip?dl=0

**Comment by aWhisper20** [comment] 2021-12-28 02:13
https://youtu.be/F9BFnt3xUX4

**Comment by aWhisper20** [comment] 2021-12-28 10:26
After testing this out it seems to only occur in my server, not in single player worlds.

**Comment by mickelus** [comment] 2021-12-28 12:02
I'm getting this on servers as well. You should be able to use /reload to fix it until it's patched.

**Comment by mickelus** [comment] 2021-12-29 02:10
Should be fixed in 4.1.2.

**Closed by mickelus** 2021-12-29 02:10 UTC
Labels: bug, Needs refinement
