### ISSUE TITLE
[Bug] getting two cobblestone through a stone pickaxe grants the "thermal transfer" advancement

### ISSUE THREAD

**Issue by kuba26038** [mickelus/tetra#736] opened 2023-07-21 16:29 UTC
### Observed behaviour

i load a new world, open a starter chest, mine two blocks of stone and i'm granted the "thermal transfer" advancement

### Expected behaviour

the advancement should be only granted by aquiring the thermal cell, and not for mining cobblestone

### Steps to reproduce

1- install tetra and mutil
2- create a world with cheats
3- give yourself a stone pickaxe
4- mine 2 blocks of stone with it

### Tetra version

tetra-1.19.2-5.3.1

### mutil/mGui version

mutil-1.19.2-5.1.0

### Forge version

43.2.18

**Comment by mickelus** [comment] 2023-07-22 18:59
Duplicate of #733, closing.

**Closed as not planned by mickelus** 2023-07-22 18:59 UTC
Labels: bug
