### ISSUE TITLE
[1.16.4][Enigmatica 6 Mod-Pack]  Unable to repair tools. 

### ISSUE THREAD

**Issue by JayOlino** [mickelus/tetra#321] opened 2021-01-19 16:33 UTC
## Bug Report

**Observed Behaviour**
If we deploy our Tetra-Tool into the Tetra-"Workbench" then we have the repair-button, which requests a Tier 0 Hammer.
Also I have in my inventory a Tier 4 Hammer and can  attach new part, but Repair isn't working.

Found on my Serverlog following:

`[19Jan2021 17:23:06.075] [Server thread/INFO] [pneumaticcraft/]: 30 active Amadron offers to sync to clients
[19Jan2021 17:25:01.125] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at se.mickelus.tetra.module.schematic.ConfigSchematic.isApplicableForItem(ConfigSchematic.java:146) ~[tetra:3.5.3]
	at se.mickelus.tetra.module.SchematicRegistry.lambda$getAvailableSchematics$11(SchematicRegistry.java:139) ~[tetra:3.5.3]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_275]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_275]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_275]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) ~[?:1.8.0_275]
	at se.mickelus.tetra.module.SchematicRegistry.getAvailableSchematics(SchematicRegistry.java:140) ~[tetra:3.5.3]
	at se.mickelus.tetra.blocks.workbench.action.RepairAction.canPerformOn(RepairAction.java:30) ~[tetra:3.5.3]
	at se.mickelus.tetra.blocks.workbench.WorkbenchTile.lambda$performAction$5(WorkbenchTile.java:159) ~[tetra:3.5.3]
	at java.util.Optional.filter(Optional.java:178) ~[?:1.8.0_275]
	at se.mickelus.tetra.blocks.workbench.WorkbenchTile.performAction(WorkbenchTile.java:159) ~[tetra:3.5.3]
	at se.mickelus.tetra.blocks.workbench.action.WorkbenchActionPacket.handle(WorkbenchActionPacket.java:47) ~[tetra:3.5.3]
	at se.mickelus.tetra.network.PacketHandler.lambda$onMessage$2(PacketHandler.java:79) ~[tetra:3.5.3]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
	at se.mickelus.tetra.network.PacketHandler.onMessage(PacketHandler.java:77) ~[tetra:3.5.3]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_275]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[forge:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_275]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

**Expected Behaviour**
I would say not receiving the NPE and also to repair our tools

**Minimal setup needed to reproduce**
Just use the "Enigmatic 6" Modpack

**Comment by mickelus** [comment] 2021-01-21 22:40
Unable to reproduce and the "Steps to reproduce" is missing, closing.

I need the fields in the template to fix the bugs, they're not there for fun. Closing, reply once you've updated the issue and I can reopen.

**Closed by mickelus** 2021-01-21 22:40 UTC
