### ISSUE TITLE
[Bug] Neve can go to upper levels apart of  4

### ISSUE THREAD

**Issue by RubenPX** [mickelus/tetra#794] opened 2024-01-13 20:03 UTC
### Observed behaviour

When i try to upgrade hammer to level 4 (Obsidian) it require a hammer with level 6

### Expected behaviour

Maybe doungrade required level to 3 to make posible upgrade to level 4

### Steps to reproduce

1. Put hammer of level 3 into tetra workbench
2. Try to upgrade hammer to level 4

### Tetra version

5.6.0

### mutil/mGui version

5.2.0

### Forge version

1.19.2

### Other mods

- Tetra Delight

### Screenshot

![image](https://github.com/mickelus/tetra/assets/23123160/e277f434-4bc9-494d-8bc2-e1b9a1d7cb5c)

**Comment by mickelus** [comment] 2024-01-13 21:18
Observed behaviour matches intended behaviour, read the advancements if you are struggling with progression. Closing.

**Closed as completed by mickelus** 2024-01-13 21:18 UTC
Labels: bug
