### ISSUE TITLE
[Bug] Item Rendering makes game lag

### ISSUE THREAD

**Issue by Floatttttt** [mickelus/tetra#655] opened 2022-08-15 17:04 UTC
### Observed behaviour

If the tool/weapon that has been edited by tetra is rendered, the fps will be much lower. For example, I hold the tool just like normal, and the fps will keep 10 even less

### Expected behaviour

Fix up the rendering bug

### Steps to reproduce

1.Place a vanilla tool/weapon in the workbench and edit it
2.Pick up the tool/weapon that has been edited
3.when it is rendered, the fps becomes much lower

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

1.18.2-40.1.69

**Comment by SeanChengN** [comment] 2022-08-19 07:58
#624

**Comment by Floatttttt** [comment] 2022-08-19 11:21
OK, thx

**Comment by mickelus** [comment] 2022-11-11 11:04
Closing, duplicate of #624

**Closed as completed by mickelus** 2022-11-11 11:04 UTC
Labels: bug
