### ISSUE TITLE
dupe any stackable item in belt pouch

### ISSUE THREAD

**Issue by KySoto** [mickelus/tetra#289] opened 2021-01-03 03:15 UTC
## Bug Report

**Observed Behaviour**
when shift clicking an item to the belt pouch, then shift clicking a second item into the belt pouch it adds the second item to the first items stack.

**Expected Behaviour**
shift click an item into the belt pouch and it works, then shift click a second item and it doesn't go into the first items stack.

**Minimal setup needed to reproduce**

- Forge version: 1.16.4  35.1.28
- Tetra version: tetra-1.16.4-3.4.0.jar
- Tetra configuration: https://gist.github.com/KySoto/39cc2e27c7ec4ed8ce29d7354198d8ec
- Other mods:
Mod Pack Valhelsia 3.1.2 https://www.curseforge.com/minecraft/modpacks/valhelsia-3/files/3152400

**Steps to reproduce**

**Comment by KindarConrath** [comment] 2021-01-03 05:37
I found this to be true with arrows, but so far not other items
(Items attempted shift+b cobblestone onto a diamond, result 1 diamond, 63 cobblestone)

but for arrows, it will convert regular arrows to special arrows or special arrows to regular arrows.

**Comment by KySoto** [comment] 2021-01-03 06:41
i just did a video to show you it works on pretty much anything stackable. i lost an item that wasnt stackable to that too.

**Comment by KySoto** [comment] 2021-01-03 06:42
i just did a video to show you it works on pretty much anything stackable. i lost an item that wasnt stackable to that too.

https://user-images.githubusercontent.com/835408/103473277-b5a04e80-4d4b-11eb-9435-f894994a5087.mp4

**Comment by mickelus** [comment] 2021-01-03 14:22
I'm unable to reproduce this, please fill out "Steps to reproduce". Are all mods from valhelsia required to be able to reproduce this, or can you do it with just tetra?

**Comment by KySoto** [comment] 2021-01-03 19:13
steps to reproduce:
make leather tier belt
add leather pouch
add cloth quiver
add quicklatch to cloth quiver
upgrade to shulker
add potion pouch
click drop several items that are not cobblestone or diamonds into leather pouch storage till two slots are left (its worked with more or less)
open it using alt + b
hold shift key down
shift click diamond into pouch
shift click stack of cobble into pouch
let go of shift
you have a stack of diamonds and one cobble stone.

i dont know if all mods are required, but since you just said you cant reproduce it, i will assume that is a yes.

**Comment by KindarConrath** [comment] 2021-01-03 19:24
I'm going to create a separate issue for mine but reference this issue as they appear to be similar but a separate bug

**Comment by KindarConrath** [comment] 2021-01-03 19:59
minimum steps to reproduce

Minimal setup needed to reproduce

Forge version: 35.1.29
Tetra version: 3.4.0
Tetra configuration: default
Other mods: FTB GUI Library, FTB Essentials, Just Enough Items, mgui

Steps to reproduce
Craft belt 
upgrade to wool sash
add wool pouch & wool potion bag
place (drop or shift click) 1 item into first pouch slot
place (drop or shift click) 64x stack of different item into first slot on top of 1 item
1st item stack filled instead of swapping or doing nothing

**Comment by mickelus** [comment] 2021-01-03 22:51
Can you check if this still persists in 3.5.0?

**Comment by KindarConrath** [comment] 2021-01-03 23:12
Tested, appears to be fixed.

**Comment by mickelus** [comment] 2021-01-04 16:05
Noice, closing then!

**Closed by mickelus** 2021-01-04 16:05 UTC
Labels: Needs refinement, bug
