### ISSUE TITLE
Tetra tag errors/world gen issues crash server

### ISSUE THREAD

**Issue by viveleroi** [mickelus/tetra#248] opened 2020-11-18 22:01 UTC
## Bug Report

**Observed Behaviour**

My custom modpack locks up and crashes on terrain gen after a tick took 60 seconds. I believe this to be related to, or caused by tetra because I always see the same messages in console before the server is killed, and removing tetra without making any other changes appears to have resolved it.

Messages that appear in console: https://hastebin.com/alebugolan.less

Crash log: https://hastebin.com/kojatecima.properties

**Expected Behaviour**
No freezes/crashes.

**Minimal setup needed to reproduce**

- Forge version: forge-1.15.2-31.2.45
- Tetra version: tetra-1.15.2-2.18.1.jar
- Tetra configuration: default
- Other mods:

```
QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
Cucumber-1.15.2-3.0.9.jar Cucumber Library {cucumber@3.0.9 DONE}
pamhc2trees-1.15.2-1.0.7.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
scenic-1.15.2-1.0.2.jar Scenic {scenic@1.15.2-1.0.2 DONE}
Bountiful Baubles-1.15.2-0.0.1.jar Bountiful Baubles {bountifulbaubles@NONE DONE}
jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
metalbarrels-2.2.jar Metal Barrels {metalbarrels@2.2 DONE}
Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
Neat 1.6-22.jar Neat {neat@1.6-22 DONE}
create-mc1.15.2_v0.2.4e.jar Create {create@mc1.15.2_v0.2.4e+custom DONE}
BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
ForgeEndertech-1.15.2-6.0.4.0-build.0044.jar Forge Endertech {forgeendertech@6.0.4.0 DONE}
XaerosWorldMap_1.11.0_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.11.0 DONE}
mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 DONE}
CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
comforts-FORGE-1.15.2-2.0.0.4.jar Comforts {comforts@FORGE-1.15.2-2.0.0.4 DONE}
SimpleStorageNetwork-1.15.2-1.0.1.jar Simple Storage Network {storagenetwork@1.15.2-1.0.1 DONE}
premium-wood-1.15.2-1.1.1.jar Premium Wood {premium_wood@1.1.1 DONE}
decorative_blocks-1.15.2-1.7.jar Decorative Blocks {decorative_blocks@1.7 DONE}
AdHooks-1.15.2-5.1.0.0-build.0046.jar Advanced Hook Launchers {adhooks@5.1.0.0 DONE}
DungeonCrawl-1.15.2-2.1.1.jar Dungeon Crawl {dungeoncrawl@2.1.1 DONE}
betteranimalsplus-1.15.2-10.0.0.jar Better Animals Plus {betteranimalsplus@10.0.0 DONE}
Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
Apotheosis-1.15.2-3.3.8.jar Apotheosis {apotheosis@3.3.8 DONE}
mcw-doors-1.0.1fix-mc1.15.1-2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
mapperbase-1.15.2-1.1.1.0.jar Mapper Base {mapperbase@1.15.2-1.1.1.0 DONE}
additional_lights-1.15.2-2.0.2.jar Additional Lights {additional_lights@2.0.2 DONE}
Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
WAWLA-1.15.2-3.0.4.jar WAWLA {wawla@3.0.4 DONE}
trash-1.15.2-0.2.0.jar Trash {trash@1.15.2-0.2.0 DONE}
ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
traverse-1.15.2-3.2.0.jar Traverse {traverse@1.15.2-3.2.0 DONE}
JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
mysticalworld-1.15.2-2.1.3.jar Mystical World {mysticalworld@1.15.2-2.1.3 DONE}
Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
forge-1.15.2-31.2.45-universal.jar Forge {forge@31.2.45 DONE}
Atum-1.15.2-2.1.10.jar Atum 2 {atum@1.15.2-2.1.10 DONE}
ruins-1.15.2.1.jar Ruins {ruins@1.15.2.1 DONE}
Bones-1.15.2-1.3.2.jar Bones {bones@1.15.2-1.3.2 DONE}
mysticallib-1.15.2-2.0.1.jar Mystical Lib {mysticallib@1.15.2-2.0.1 DONE}
absentbydesign-1.15.2-1.1.1.jar Absent By Design Mod {absentbydesign@1.15.2-1.1.1 DONE}
structure-gel-api-1.15.2-1.1.0.jar Structure Gel API {structure_gel@1.1.0 DONE}
MysticalAgriculture-1.15.2-3.0.10.jar Mystical Agriculture {mysticalagriculture@3.0.10 DONE}
ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
forge-1.15.2-31.2.45-server.jar Minecraft {minecraft@1.15.2 DONE}
cofh_core-1.15.2-1.0.0.jar CoFH Core {cofh_core@1.0.0 DONE}
ensorcellation-1.15.2-1.0.0.jar Ensorcellation {ensorcellation@1.0.0 DONE}
The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
FarmersDelight-1.15.2-0.2.3.jar Farmer's Delight {farmersdelight@1.15.2-0.2.3 DONE}
useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 DONE}
swingthroughgrass-1.15.2-1.4.1.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.1 DONE}
embellishcraft-1.15.2-2.2.1.0.jar EmbellishCraft {embellishcraft@1.15.2-2.2.1.0 DONE}
AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
ToolBelt-1.15.2-1.14.2.jar Tool Belt {toolbelt@1.14.2 DONE}
valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
toughnessbar-5.0.jar Toughness Bar {toughnessbar@5.0 DONE}
simplefarming-1.15.2-1.3.4.jar Simple Farming {simplefarming@1.15.1-1.3.4 DONE}
pamhc2foodextended-1.15.2-1.0.0.jar Pam's HarvestCraft 2 Food Extended {pamhc2foodextended@version DONE}
curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
tetra-1.15.2-2.18.1.jar Tetra {tetra@1.15.2-2.18.1 DONE}
SpartanShields-1.15.2-2.1.0.jar Spartan Shields {spartanshields@2.1.0 DONE}
Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 DONE}
Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
Xaeros_Minimap_20.26.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.26.0 DONE}
JAOPCA-1.15.2-3.2.0.15.jar JAOPCA {jaopca@3.2.0.15 DONE}
pamhc2foodcore-1.15.2-1.1.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
FastWorkbench-1.15.2-3.1.1.jar FastWorkbench {fastbench@3.1.1 DONE}
autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
StorageDrawers-1.15.2-7.0.3.jar Storage Drawers {storagedrawers@1.15.2-7.0.3 DONE}
moarboats-1.15.2-7.0.0.1.jar Moar Boats {moarboats@1.15.2-7.0.0.1 DONE}
FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
SpartanWeaponry-1.15.2-2.0.0-beta-1.jar Spartan Weaponry {spartanweaponry@2.0.0 beta 1 DONE}
mcws-roofs-1.15.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
Aquaculture-1.15.2-2.0.22.jar Aquaculture 2 {aquaculture@1.15.2-2.0.22 DONE}
FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
exoticbirds-1.15.2-1.0.3.jar Exotic Birds {exoticbirds@1.0.3 DONE}
overloadedarmorbar-4.0.0.jar Overloaded Armor Bar {overloadedarmorbar@4.0.0 DONE}
OresAboveDiamonds-1.15.2_v5.1.1.jar Ores Above Diamonds {oresabovediamonds@5.1.1 DONE}
BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 DONE}
WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
lumberjack-2.0.1.jar LumberJack {lumberjack@2.0.1 DONE}
```

**Steps to reproduce**
Travel around, generating chunks. Before long the console messages appear, clients time out, and after 60 seconds the server is killed and "crashed".

**Comment by mickelus** [comment] 2020-12-25 13:27
Is this the minimal set of mods required to reproduce this? Afaik that error message is due to tile entities in tetra not having datafixers registered, a datafixer is typically used (I think) to migrate data when the data format for a tile entity changes between versions. From what I've seen that shouldn't do anything, and should definitely not cause a hang.

**Comment by mickelus** [comment] 2021-03-09 12:55
Closing as this has been in need of refinement for a long time with no progress. Feel free to update & comment on the issue and I'll reopen it.

**Closed by mickelus** 2021-03-09 12:55 UTC
Labels: Needs refinement
