### ISSUE TITLE
[Bug] Tetra isnt working on "All the mods 7" modpack + few otrher mods

### ISSUE THREAD

**Issue by GObeynew** [mickelus/tetra#707] opened 2023-03-19 20:25 UTC
### Observed behaviour

While the game launches fine, and tetra is loaded (visible through mod list), it does not show in game. This is revealed through not being able to craft items or not being able to spawn them via creative menu.

### Expected behaviour

Any of tetra features should be accesable.

### Steps to reproduce

1. Play on uploaded modpack
2. Try to acces any of the tetra issues

### Tetra version

4.10.1

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.2.0

### Other mods

[All the Mods 7 - ATM7-0.4.34.zip](https://github.com/mickelus/tetra/files/11012207/All.the.Mods.7.-.ATM7-0.4.34.zip)

This is the modpack for the curse forge app.

**Comment by mickelus** [comment] 2023-03-19 20:46
Closing, unable to reproduce.

**Closed as completed by mickelus** 2023-03-19 20:46 UTC
Labels: bug
