### ISSUE TITLE
[Bug] Game Crash When Mining for cobblestone

### ISSUE THREAD

**Issue by Hikari16665** [mickelus/tetra#777] opened 2023-12-09 06:45 UTC
### Observed behaviour

the game crashed when I was using a diamond dolabra to dig for cobblestone.

### Expected behaviour

Subsequent testing found that any quality pickaxe would cause the game to crash...

### Steps to reproduce

1.Craft a wooden pickaxe
2.Using wooden pickaxe to dig stones
3.The game crashed.

### Crashlog

https://mclo.gs/W7j7n1G

### Tetra version

6.1.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1-47.1.0

### Other mods

![image](https://github.com/mickelus/tetra/assets/124548189/cdf178f6-b4c8-41d8-b49f-a2b129996044)

**Comment by mickelus** [comment] 2023-12-22 13:35
I'm unable to reproduce this. You've listed no other mods but the crash log contains a long list of mods. Closing, we can look into reopening this if you can provide a minimal list of mods required to reproduce the issue.

**Closed as not planned by mickelus** 2023-12-22 13:35 UTC
Labels: bug
