### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by J4kulMei** [mickelus/tetra#518] opened 2021-11-10 07:51 UTC
### Observed behaviour

I added tetra and Inventory Tweaks Renewed. When I open the workbench and sort my inventory, the items dupe.

### Expected behaviour

I did not expect my items to dupe.

### Steps to reproduce

1. Open the workbench
2. Press the key that sorts inventory
3. The items dupe

### Tetra version

tetra-1.16.5-3.19.0

### mGui version

mgui-1.16.5-3.3.0

### Forge version

1.16.5 - 36.1.32

### Other mods

Inventory Tweaks Renewed. 
invtweaks-1.16.4-1.0.1

**Comment by mickelus** [comment] 2021-12-01 22:21
Closing, duplicate of #431.

**Closed by mickelus** 2021-12-01 22:21 UTC
Labels: bug
