### ISSUE TITLE
[Bug] Crash upon putting two Tetra items into a crafting grid

### ISSUE THREAD

**Issue by BDMorrell** [mickelus/tetra#698] opened 2023-02-12 01:37 UTC
### Observed behaviour

Putting two Tetra items (only tested two-sided tools) into a crafting square will crash the game.

The crafting square can be the player's 2&times;2 square, the crafting table's 3&times;3 square, or a crafting square from another mod. (The *other mod* I'm talking about was when this crash bug was initially discovered by shift-clicking items into a backpack's crafting square. This crash can be replicated using only the mods required to enable Tetra, so the specifics of other mods may be irrelevant.)

### Expected behaviour

I expected that putting Tetra items into a crafting grid (ie, by mistake) would not crash the game, but result in normal invalid/incomplete recipe behavior.

### Steps to reproduce

1. Try to craft something by using two Tetra items as ingredients.
2. There is no step two. The game crashed when you clicked the second Tetra item into whatever crafting grid you were using.

### Specific lab-condition steps to reproduce

This crash can be replicated with a Forge (24.2.0) mod pack for Minecraft (1.19.2) that only contains the mod files `multi-1.19.2-5.1.0.jar` and `tetra-1.19.2-5.0.1.jar`. Make a new world that is a creative, peaceful, flat world (default); though I also disabled `doWeatherCycle` and `doDaylightCycle`.

1. Get a bunch of oak logs from the creative inventory.
4. Switch to survival so that the player crafting is available.
5. Make a bunch of oak planks, 2 crafting tables, 8 sticks.
6. Place a crafting table.
7. Use crafting table to make a Tetra hammer, a wooden axe, and two wooden pickaxes.
8. Place the other crafting table, using the hammer on it to make a Tetra crafting table.
9. Use the Tetra table to replace the handle off both pickaxes with ones made with oak planks. At this point, you now have two Tetra items (both are wooden pickaxes).
10. Use the normal workbench (or the player 2&times;2 crafting grid) to try to craft the two Tetra pickaxes.

### Crashlog

https://gist.github.com/BDMorrell/70510f2fd36cb2c3373f983912f077cc

### Tetra version

5.1.0

### mutil/mGui version

5.0.1

### Forge version

43.2.0

### Other mods

I tested that this crash happens on a new Forge modpack for Minecraft 1.19.2. The only mod I manually added was Tetra, and Forge added "multi". No other mods need to be added.

**Comment by BDMorrell** [comment] 2023-02-12 02:06
The specific underlying bug may also be causing #688, #693, #694, #696, and #697. These all seem to be crashes for invalid Tetra items, but they are all being encountered from different sources.

Sorry for not including this information in my initial post. I hope this doesn't cause too much notification noise!

**Comment by LegoMaster3650** [comment] 2023-02-12 17:52
Yeah it seems my report in #696 applies in quite a few situations, here it's probably the durability tag being set or something causing the item to meet the "has a tag but no modular item tags" crash criteria. (I read the crash report and I am 99% certain it's the same root cause)

**Comment by mickelus** [comment] 2023-02-27 23:16
Should be fixed in 5.0.2!

**Closed as completed by mickelus** 2023-02-27 23:16 UTC
Labels: bug
