### ISSUE TITLE
[Bug] tetra crashing game on common_setup phase

### ISSUE THREAD

**Issue by epicyeeto** [mickelus/tetra#564] opened 2022-01-30 21:18 UTC
### Observed behaviour

my modpack keeps crashing
![image](https://user-images.githubusercontent.com/73504007/151718150-38d4b59e-3a57-4bbd-be41-3514b75d18c4.png)
idk why it is happening

### Expected behaviour

to work

### Steps to reproduce

1.play mod

### Crashlog

https://gist.github.com/epicyeeto/8ac031e96aea5f58a75618c2167ad7a6

### Tetra version

4.5.0

### mGui version

4.2.0

### Forge version

39.0.62

### Other mods

Nimble (Forge) (by Snownee_)
Create (by simibubi)
Extra Disks (by MelanX)
Dungeons Enhanced (by Valarauko9)
Alternate Current (by SpaceWalkerRS)
Hostile Neural Networks (by Shadows_of_Fire)
REI Compatibility Workaround (by shedaniel)
Structure Gel API (by ModdingLegacy)
Nuclear Science (by aurilisdev)
Advanced Peripherals (by srrendi)
BetterF3 (by cominixo)
Assembly Line Machines (by haydenman2)
Tetra (by mickelus)
Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
Occultism (by kli_kli)
Scalable Cat's Force (by Kotori316)
Not Enough Crashes (Forge) (by NatanFudge)
Repurposed Structures (Forge) (by telepathicgrunt)
Waystones (by BlayTheNinth)
FPS Reducer (by bre2el)
Placebo (by Shadows_of_Fire)
Flywheel (by jozufozu)
Beyond Earth: Giselle Addon (by 지젤쟝다)
Crossroads MC (by Technomancer_isTaken)
Integrated Dynamics (by kroeser)
Equipment Compare (by Grend_G)
CC: Tweaked (by SquidDev)
Snad (by TheRoBrit)
Forbidden and Arcanus (by cesar_zorak)
Industrial Reborn (by Maciej916)
Catalogue (by MrCrayfish)
Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)
Ranged Pumps (by raoulvdberge)
Amplified Nether (by Starmute)
Dynamic View[Forge/Fabric] (by someaddon)
Structurize (by H3lay)
Krypton Reforged (by TeamDeusVult)
Corpse (by henkelmax)
Essentials (by Technomancer_isTaken)
ExtraStorage (by 3divad99)
Refined Storage (by raoulvdberge)
Curios API (Forge) (by TheIllusiveC4)
Chargers (by GoryMoon)
Immersive Engineering (by BluSunrize)
Dungeon Crawl (by xiroc_)
TerraBlender (Forge) (by TheAdubbz)
Crafting Tweaks (by BlayTheNinth)
MineColonies for ComputerCraft (by uecasm)
Ore Excavation (by Funwayguy)
Mob Grinding Utils (by vadis365)
When Dungeons Arise - Forge! (by Aureljz)
Common Capabilities (by kroeser)
Farmer's Delight (by vectorwing)
Quark (by Vazkii)
Multi-Piston (by H3lay)
AutoRegLib (by Vazkii)
Configured (by MrCrayfish)
Engineer's Decor (by wilechaote)
Nature's Aura (by Ellpeck)
Architectury API (Forge) (by shedaniel)
Mining Gadgets (by Direwolf20)
Xaero's World Map (by xaero96)
Valhelsia Core (by ValhelsiaTeam)
Biomes O' Plenty (by Forstride)
Compact Machines (by davenonymous)
Cyclic (by Lothrazar)
FerriteCore (Forge) (by malte0811)
Selene Lib (by MehVahdJukaar)
Kotlin for Forge (by thedarkcolour)
Ars Nouveau (by baileyholl2)
Beyond Earth (by mrscauthd)
Creative Wireless Transmitter (by Ultramegaaa)
Gauges and Switches (by wilechaote)
Gobber [FORGE] (by kwpugh)
AppleSkin (by squeek502)
Dash (by ModdingLegacy)
Fast Leaf Decay (by olafskiii)
Apotheosis (by Shadows_of_Fire)
Balm (Forge Edition) (by BlayTheNinth)
Cloth Config API (Forge) (by shedaniel)
Convenient Curios Container (by LeoBeliik)
SlashBlade (by flammpfeil)
Roughly Enough Items Fabric/Forge (REI) (by shedaniel)
Patchouli (by Vazkii)
No Null Processors (by telepathicgrunt)
Adorn (Forge) (by Juicebus)
MineColonies (by H3lay)
Iron Jetpacks (by BlakeBr0)
Iceberg (by Grend_G)
Enhanced Nature (by XxRexRaptorxX)
Additional Enchanted Miner (by Kotori316)
Domum Ornamentum (by OrionOnline)
Leap (by ModdingLegacy)
Mystical Agriculture (by BlakeBr0)
mutil (by mickelus)
Phosphor Reloaded (by Reforged89)
Supplementaries (by MehVahdJukaar)
Decorative Blocks (by stohun)
Enhanced Farming (by Mrbysco)
Refined Storage Addons (by raoulvdberge)
Cyclops Core (by kroeser)
Mouse Tweaks (by YaLTeR)
Electrodynamics (by aurilisdev)
Bonsai Trees 3 (by davenonymous)
Chisels & Bits - For Forge (by AlgorithmX2)
Clumps (by Jaredlll08)
GeckoLib (by ThanosGecko)
Xaero's Minimap (by xaero96)
Cucumber Library (by BlakeBr0)
BlockUI (by H3lay)
Meet Your Fight (by Lykrast)
Neat (by Vazkii)
Assembly Lines (by aurilisdev)
Feature NBT Deadlock Be Gone (by telepathicgrunt)
The Wild Update 1.19 [FORGE] (by ZainJx81)
Nullscape ~ End Reborn (by Starmute)
Ballistix (by aurilisdev)
Jade 🔍 (by Snownee_)
Mahou Tsukai (by stepcros)
Ring of Repair [FORGE] (by kwpugh)
idk how to show mod version

**Comment by epicyeeto** [comment] 2022-01-31 02:10
this is going to take a long long time for someone to respond

**Comment by mickelus** [comment] 2022-02-07 19:02
Seems to be caused by some weird interaction between a mixin in beyond earth and optifine, supposedly fixed here https://github.com/MrScautHD/Beyond-Earth/commit/7cc823ebd57351dea423166aa374c789f5e70dd0. Closing.

**Closed as completed by mickelus** 2022-02-07 19:02 UTC
Labels: bug
