### ISSUE TITLE
[Bug] Item Duplication

### ISSUE THREAD

**Issue by BugTrackerGuy** [mickelus/tetra#519] opened 2021-11-10 08:04 UTC
### Observed behaviour

https://user-images.githubusercontent.com/94040719/141073386-936a1c46-7390-4f76-9953-586c392cdd17.mp4

Encountered it while I was breaking some geode and since I have a habit of constantly clicking the sort inventory button it led me to this bug. It seems to work with many other items.

### Expected behaviour

Items inside my inventory getting sorted normally.

### Steps to reproduce

1. Have items inside your inventory.
2. Open the workbench UI.
3. Spam the Inventory Sort button.

### Tetra version

3.19.0

### mGui version

3.3.0

### Forge version

1.16.5 - 36.2.8

### Other mods

Tetra 3.19.0
Inventory Tweaks 1.0.1

**Comment by mickelus** [comment] 2021-12-01 22:21
Closing, duplicate of #431.

**Closed by mickelus** 2021-12-01 22:21 UTC
Labels: bug
