### ISSUE TITLE
Startup Crash with Foamfix and Unlimited Chisel Works

### ISSUE THREAD

**Issue by zauberparacelsus** [mickelus/tetra#67] opened 2019-09-28 19:07 UTC
## Bug Report

**Observed Behaviour**
When Tetra is installed alongside Foamfix and/or Unlimited Chisel Works, minecraft crashes during startup.  When Tetra is uninstalled afterwards, the crash does not occur.

**Minimal setup needed to reproduce**
- Forge version: 1.12.2  14.23.5.2838
- Other mods:
- FoamFix 7.7.4
- Unlimited Chisel Works 0.2.4

**Steps to reproduce**
- Install the mods above and attempt to start minecraft

**Additional Info**
- Crash Log: https://paste.dimdev.org/alezovanoz.mccrash

**Comment by mickelus** [comment] 2019-09-28 20:28
I'm unable to reproduce this with the stated setup.

**Comment by mickelus** [comment] 2019-10-12 15:05
Closing this. Feel free to reopen if you manage to produce a minimal setup with a matching crashlog.

**Closed by mickelus** 2019-10-12 15:05 UTC
Labels: unclear
