### ISSUE TITLE
Some slots are unusable with a mesh pouch.

### ISSUE THREAD

**Issue by Edulml** [mickelus/tetra#432] opened 2021-05-26 03:40 UTC
## Bug Report

**Observed Behaviour**
When upgrading a toolbelt with a mesh pouch, the UI would suggest that the upper five slots are available, but there is no way to put items in it. In the screenshot there is also a quiver but I have also tried out a belt that only has the mesh pouch.

![image](https://user-images.githubusercontent.com/26638760/119599185-7e8e1080-bdb2-11eb-81fb-4e7defbc633e.png)

**Expected Behaviour**
It is expected that all of the slots shown in the UI are available. If for balance reasons they shouldn't be available then the UI needs to be tweaked accordingly.

**Minimal setup needed to reproduce**
- Forge version: 1.16.5 - 36.1.23
- Tetra version: 3.11.1
- Tetra configuration: Default.
- Other mods: It shouldn't be an interaction with another mod.

**Steps to reproduce**
Simply upgrade a toolbelt with a mesh pouch and try to put an item on the highlighted slots.

**Comment by mickelus** [comment] 2021-05-26 12:29
> If for balance reasons they shouldn't be available then the UI needs to be tweaked accordingly

What does "tweaked accordingly" mean?

Furthermore "Other mods: It shouldn't be an interaction with another mod" will probably lead to issues being instantly closed in the future, **the fields are there because I need them, you lack the insight to decide which ones are relevant and thefore you fill out all of them**

"Steps to reproduce" is also incredibly lacking.

**Comment by Edulml** [comment] 2021-05-26 14:51
Alright, here's some further clarification.

When I said "Tweaked accordingly" I meant that if the mesh pack can only store 13 items, then I shouldn't be shown 18 slots with 5 of those being unusable. It's confusing.

The steps to reproduce is that short because I don't know what else there is to say about this. I just tried to use my toolbelt normally and I end up with those 5 unusable slots, the slots I can use are precisely the amount the mesh pouch module stated, but the GUI is drawing more that can't be used. 
I will add that I tried upgrading a second belt that I used exclusively for extra storage with a mesh pouch + 2 wool pouches and in this case it did draw the correct amount of slots in the GUI.

And finally, can you tell me a method to more easily get my entire mod list? I have tried looking at the logs for a list of the mods loaded, looking for an option in the game menus, and I couldn't find anything. I'd rather just leave this vague and have you close the issue than manually type the list of each and every mod I'm using

**Comment by mickelus** [comment] 2021-06-01 18:27
How should it work then? I considered several approaches when I changed the UI, they all had their drawbacks. I don't have control over the content in tetra, a solution cannot be to change the content or for the UI to assume that the number of slots is a multiple of some value.

**Comment by mickelus** [comment] 2021-06-01 18:31
You can typically find a mod list in crash logs, or you could do something like this: https://superuser.com/questions/490306/how-do-i-copy-all-file-names-in-a-folder-to-notepad/490314

**Comment by mickelus** [comment] 2021-12-29 22:52
Closing this as there's been several months without activity.

**Closed by mickelus** 2021-12-29 22:52 UTC
Labels: Needs refinement
