### ISSUE TITLE
Workbench Becomes Unusable Forge

### ISSUE THREAD

**Issue by Zachattack525** [mickelus/tetra#356] opened 2021-02-11 00:24 UTC
## Bug Report

**Observed Behaviour**
As stated, whenever I attempt to create a workbench, it becomes a forge hammer block, but only on my end. for other people is is still a workbench, but as far as my game is concerned, it is a forge hammer through and through, even taking as long to break as one. It will not create the multiblock. Even workbenches spawned in and placed would immediately turn into forges.

**Expected Behaviour**
I had expected the mod to work as normal and let me use the mod properly.

**Minimal setup needed to reproduce**

- Forge version: 1.16.4 - 35.1.36
- Tetra version: 3.6.0
- Tetra configuration: I have changed nothing about the configuration
- Other mods: 
- Bookshelf
- Compact Machines
- Cucumber Library
- Curious API (Forge)
- Gravestones Mod
- Inventory Pets
- Just Enough Items (JEI)
- Polymorph (Forge)
- Refined Storage
- Xaero's World Map
- YUNG's Better Mineshafts
- [FORGE] Iron Furnaces
- Appleskin
- Applied Energistics 2
- Astral Sorcery
- Blood Magic
- Botania
- Botania Additions
- Botania: Garden of Glass
- BountifulBaubles
- CC: Tweaked
- Chisels & Bits
- CodeChicken Lib 1.8.+
- CoFH Core
- Collective
- Colossal Chests
- Create
- Cyclops Core
- Ender Storage 1.8.+
- Extreme Reactors
- Fast Leaf Decay
- Inventory Tweaks Renewed
- Iron Chests
- Just Enough Resources (JER)
- mGui
- Morpheus
- Mystical Agriculture
- Mystical Agradditions
- ObserverLib
- Overloaded Armor Bar
- Patchouli
- Pneumaticraft: Repressurized
- Psi
- Runelic
- Sound Filters
- Tetra
- Thermal Expansion
- Thermal Foundation
- Torchmaster
- Tree Harvester
- Waystones
- Xaero's Minimap
- ZeroCore 2

**Steps to reproduce**
I had removed a few mods for a server at the request of a friend, Extreme Reactors, Thermal Foundation, Thermal Expansion, and Applied Energistics 2. After having issues connecting to each other, we readded them, and now I have this issue.

**Comment by mickelus** [comment] 2021-02-12 22:18
Sounds like you messed something up when you were removing and addings mods. I can't reproduce this, installing 40-ish mods and removing/adding mods at random (unless it were exactly Extreme Reactors, Thermal Foundation, Thermal Expansion, and Applied Energistics 2?) until this occurs is not feasible.

**Comment by mickelus** [comment] 2021-03-09 12:44
Closing as this has been in need of refinement for a long time with no progress. Feel free to update & comment on the issue and I'll reopen it.

**Closed by mickelus** 2021-03-09 12:44 UTC
Labels: Needs refinement
