### ISSUE TITLE
Forge Hammer w/ BSL shaders

### ISSUE THREAD

**Issue by Cinnamon-Addict** [mickelus/tetra#405] opened 2021-05-04 21:46 UTC
## Bug Report

**Observed Behaviour**
 I was upgrading my tools with the forge hammer above ground in the desert when I noticed that the icons to remove any forge hammer upgrades were blindingly bright to the point of inability to look at it to see the icon

**Expected Behaviour**
 the sort of normal behavior of showing the cutting tool icon, maybe with a slight amount of glowing

**Minimal setup needed to reproduce**

- Forge version: 
- Tetra version:  I just used the base config, nothing changed besides the usual that tetranomcon does
- Other mods:
mods are [create, Biomes You'll go, Tetra, tetranomicon, tetra pak, Undergarden, Immersive engineering, immersive portals] 
**Steps to reproduce**
 the step by step is use a normal workbench with a forge hammer on top above ground in BYG's desert biomes during midday, add the combustion chambers then look at the forge hammer to attempt to remove the upgrades

**Comment by mickelus** [comment] 2021-06-01 18:33
Closing, duplicate of #371

**Closed by mickelus** 2021-06-01 18:33 UTC
