### ISSUE TITLE
0.15.0 Crafting errors

### ISSUE THREAD

**Issue by ejektaflex** [mickelus/tetra#23] opened 2018-09-11 09:58 UTC
Version: tetra-1.12.2-0.15.0.jar

Spawning in an iron axe and switching the head out for a tin adze head will cause the recipe to just return an iron axe when created. This also works with a lead adze head. Doing so with a wooden adze is supposedly uncraftable, although the stone adze head works.

Also, removing the storage pouch from a toolbelt keeps the toolbelt inventory, but all items are inaccessible until you re-add the pouch.

**Comment by mickelus** [comment] 2018-09-13 11:05
I missed adding the post remove cleanup when directly removing any of the toolbelt inventories, replacing them should still store excess items in your inventory. Fix should be part of the next release.

I've not been able to reproduce tin adze issue, have you noticed similar behaviour with other materials? The cause of the wooden adze not working is the same as what's causing #22.

**Comment by mickelus** [comment] 2018-09-13 23:36
Both fixed in [0.15.1](https://minecraft.curseforge.com/projects/tetra/files/2616629), no need to go into embarrasing details about the adze issue.

**Closed by mickelus** 2018-09-13 23:36 UTC
Labels: bug
