### ISSUE TITLE
bug, even with all requirements met i cannot modify any tools

### ISSUE THREAD

**Issue by Uvbnstrk2** [mickelus/tetra#779] opened 2023-12-10 09:52 UTC
### Observed behaviour

attempted to upgrade handle to oak wood, i had an stone axe (ax lvl 2, req lvl 1) and enough wood and it wouldnt let me, following this i went into creative and gave myself highest grade tools to try with, this didnt work, i also found i couldnt modify ANYTHING at all.

### Expected behaviour

upgrade handle useing 2 oak wood.

### Steps to reproduce

place any tool in workbench
attempt upgrade (with proper level tools0
note that it says you cant

### Crashlog

N/A

### Tetra version

0.39.1

### mutil/mGui version

N/A

### Forge version

1.12.2

### Other mods

xaeros minimap, worldedit, AE2, AE2 wireless crafting terminal, twilight forest, thermal innovation, thermal foundation, thermal expantion, thermal dynamics, thaumic wands, thaumic terminal, thaumicJEI, thaumic augmentation, thaumic additions, thaumcraft, supermartin642 lib, somanyenchantments, rf tools dimensions, rf tools, redstone flux, potion fingers, placebo, password's lib, orespawn, not enough energistics, multitools, MMD lib, minetweakerrecipemaker, mcjty lib, mantle, llibrary, just enough energistics, jei, ice and fire, hwyla, ftb ultimine, foamfix, eye of dragons, extra cpus, enchanting plus, elevators, CoFH world, CoFH core, code chicken lib, chunkloaders, champions, censored asm, bring me the rings, bookshelf, oh the biomes you'll go, baubles, base metals, autoreg lib, apotheosis, alchemistry, draconic evolution, overloaded armor bar, project intelligence

**Comment by mickelus** [comment] 2023-12-22 10:58
Unable to reproduce this issue. Closing, feel free to reopen if you're able to provide a minimal set of mods required to reproduce the issue.

**Closed as not planned by mickelus** 2023-12-22 10:58 UTC
Labels: bug
