### ISSUE TITLE
[Bug] Blocks missing mineable tag

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#580] opened 2022-02-25 00:29 UTC
### Observed behaviour

Blocks are missing the mineable block tag, such as `minecraft:mineable/axe` or `minecraft:mineable/pickaxe`

### Expected behaviour

Blocks should have these tags so they can be mined faster

### Steps to reproduce

1. Place tetra workbench or tool rack
2. Try to mine it
3. Check for tags

### Tetra version

4.7.0

### mutil/mGui version

4.4.0

### Forge version

1.18.1 - 39.0.79

**Comment by mickelus** [comment] 2022-02-25 00:56
Closing, duplicate of #560.

**Closed as completed by mickelus** 2022-02-25 00:56 UTC
Labels: bug

**Comment by WenXin20** [comment] 2022-02-25 03:37
Ah, my bad. I missed that when looking over the previous issues
