### ISSUE TITLE
[Bug] Crossbow Animation

### ISSUE THREAD

**Issue by ComfyRift** [mickelus/tetra#547] opened 2022-01-11 03:24 UTC
### Observed behaviour

Hey, this is the first time that I'm writing a bug report, I'm hoping I'm doing it right. xD
So what happened is that I was trying out the mod for 1.18.1.
When I tried loading a tetra modified crossbow in first person, it glitched to the top right of my screen.
I then got in to third person and realized that the character was not holding the crossbow like a crossbow.

So yeah that's the problem nothing mayor I think.
Oh, I was using some Resourcspacks.

![2022-01-11_04 19 36](https://user-images.githubusercontent.com/97492609/148875734-90cb2cf3-48b9-4746-8ecc-8fc1b2345db8.png)
![2022-01-11_04 19 29](https://user-images.githubusercontent.com/97492609/148875744-3f8d6a21-f96e-4d90-b5b5-9e83846094c9.png)
![2022-01-11_04 19 51](https://user-images.githubusercontent.com/97492609/148875738-0ee683cc-a5ef-4709-b8d6-bb962749a20b.png)
![2022-01-11_04 19 54](https://user-images.githubusercontent.com/97492609/148875741-c98e2fc8-055d-4fd9-8241-0f6e701c92dc.png)

### Expected behaviour

Well, that there would be a normal crossbow animation or something.

### Steps to reproduce

1. Take Crossbow
2. Modify with tetra
3. Try to load in first or third person.
4. Observe

### Tetra version

4.3.0

### mGui version

4.1.0

### Forge version

1.18.1 - 39.0.18

### Other mods

None.

**Comment by mickelus** [comment] 2022-01-16 22:22
closing, duplicate of #287.

**Closed as completed by mickelus** 2022-01-16 22:22 UTC
Labels: bug
