### ISSUE TITLE
[Bug] Crash when trying to open workbench (no such field)

### ISSUE THREAD

**Issue by Twisted-Code** [mickelus/tetra#684] opened 2023-01-04 01:58 UTC
### Observed behaviour

opening this bug report on behalf of a friend, I'm not the one experiencing the problem, but she doesn't have a github account (yet).
When she tried to click a workbench, it caused this unhandled exception, which was then caught by Not Enough Crashes:
https://bytebin.lucko.me/2R8QzUfU5m
hopefully NEC didn't obscure the important details of the crash, but I can ask my friend to try again without NEC if you would like

### Expected behaviour

don't crash, I guess.

### Steps to reproduce

1. Create a hammer
2. right-click a crafting table with it to create a workbench
3. attempt to open the workbench
4. crash
... something tells me there's a missing step here, since I don't think you would've released this version if the workbench wasn't working. Perhaps it's one of the add-ons my friend has

### Crashlog

[latest(1).log](https://github.com/mickelus/tetra/files/10340980/latest.1.log)

### Tetra version

4.10.1

### mutil/mGui version

4.5.0

### Forge version

40.1.0?

### Other mods

art of forging v1.5.5

**Comment by mickelus** [comment] 2023-02-27 23:25
Closing due to:
-  Unable to reproduce this
- The crash log link isn't working
- There are far more mods present in the latest log

Feel free to comment if you're able to provide more information.

**Closed as completed by mickelus** 2023-02-27 23:25 UTC
Labels: bug
