### ISSUE TITLE
Potential conflict with Alex's Mobs falconry hood

### ISSUE THREAD

**Issue by pm065** [mickelus/tetra#437] opened 2021-05-30 14:05 UTC
See https://github.com/NillerMedDild/Enigmatica6/issues/2307

Original poster was playing on Enigmatica 6's server, which if I'm not mistaken has the 3.9.2 version of Tetra and 1.9.1 of Alex's Mobs. The official server also has Lithium (presumably a forge port that isn't on curse yet) installed, so that may be a factor.

**Comment by mickelus** [comment] 2021-05-30 14:10
Use the bug report template in the future.

Closing, duplicate of #422.

**Closed by mickelus** 2021-05-30 14:10 UTC
