### ISSUE TITLE
[Bug] Crash upon using JEI to preview Tetra Items with Item Upgrader

### ISSUE THREAD

**Issue by Trilli** [mickelus/tetra#694] opened 2023-02-09 06:15 UTC
### Observed behaviour

Pressing the "Show uses" key in JEI on a tool now crashes the game with an out of bounds crash message

### Expected behaviour

Shows a "Default" tetra tool, like some sort of placeholder or similar to how the tetra hammers are shown

### Steps to reproduce

1. Press "Show uses" key for JEI on a modular tool with "ItemUpgrader" Installed
2. Crash

### Crashlog

https://gist.github.com/Trilli/e4358574169aa6520d491cd03d523cff

### Tetra version

5.0.1

### mutil/mGui version

5.1.0

### Forge version

1.19.2 - 43.2.4

### Other mods

Crash happens with any number of mods, from just the base to a full pack.

Related, can tools keep ItemUpgrades when turned from regular to tetra tools? The tools handle having them on them without flaw, so it would just carrying over the data, like with the apotheosis sockets, atributes, etc.

**Comment by LegoMaster3650** [comment] 2023-02-09 18:06
Just giving my input on this, as I develop Item Upgrader: It appears tetra has a safeguard against modular items with no NBT, but not one for an item with NBT that lacks any proper tetra tags. This appears to be the cause of this issue, as my mod's JEI entries all have {ItemUpgrade:"[upgrade id]"} to show the crafted upgrade (and an item with this tag was responsible for the crash according to the log)
I've also verified this isn't only my mod's fault (although I am technically messing up by triggering this bug) by removing my mod and just giving myself a modular item with an irregular tag (specifically one without any tetra tags), and that was enough to crash the game. (that world is dead now)

I'll probably make an issue on this specific issue soon, but I'm gathering a bit more information first.

**Comment by mickelus** [comment] 2023-02-27 23:17
Should be fixed in 5.0.2!

**Closed as completed by mickelus** 2023-02-27 23:17 UTC
Labels: bug
