### ISSUE TITLE
Tetra axe breaks immersive engineering wooden storage crate out of existence

### ISSUE THREAD

**Issue by silverwyrm** [mickelus/tetra#251] opened 2020-11-20 22:47 UTC
## Bug Report

**Observed Behaviour**
When attempting to break an immersive engineering crate with an axe modified with tetra, the crate will break but not appear on the ground to be picked up

**Expected Behaviour**
breaking the block and having it appear on the ground to be picked up

**Minimal setup needed to reproduce**
valhelsia 3 1.16.3

**Steps to reproduce**
this appears to occur when the swing animation doesn't complete fully. if you allow the axe to fully ready, then hold to swing through the full animation, the block will break normally. If you start swinging before the axe is "ready", or if you stop swinging and then repeat swinging immediately, the crate can break and then not appear to be picked up. this is repeatable and I was able to poof about a dozen crates

**Comment by mickelus** [comment] 2020-11-20 23:36
I doubt that the entire valhelsia 3 pack is the minimal setup required to reproduce this. What kind of axe did you use? Could this a duplicate of https://github.com/mickelus/tetra/issues/245?

**Comment by silverwyrm** [comment] 2020-11-21 00:38
> I doubt that the entire valhelsia 3 pack is the minimal setup required to reproduce this. What kind of axe did you use? Could this a duplicate of #245?

Apologies for not having a more detailed report! It does indeed appear to be linked to the emerald. Taking the emerald socket out solves the behavior.

Thank you!

**Comment by mickelus** [comment] 2020-11-21 01:20
Cool! Closing this then as it's a duplicate, follow that issue if you want a notification for when it's fixed.

Thanks for the kind words!

**Closed by mickelus** 2020-11-21 01:20 UTC
Labels: Needs refinement
