### ISSUE TITLE
Game is soft-killed when traveling to certain location

### ISSUE THREAD

**Issue by Hiranus** [mickelus/tetra#239] opened 2020-11-13 23:28 UTC
## Bug Report
I know that title is vague, sorry for that.

**Observed Behaviour**
When checking my currently generated world I found area that "soft kills" MC. I can still move around, but I can't attack any mob, can't receive any damage. When I try to break block nothing is dropped, and snow as well as grass are just "floating". See attached picture.
If I try to save and quit game is stuck in never ending "Saving world".
If I remove Tetra area that cause this issue works normally.

Crash log: 
https://pastebin.com/Fdca0kZ4
I know that there is no clear "error". Nothing else is generated in log.

**Expected Behaviour**
Problematic area works normally. I expect its issue with some dungeon generated by this mod/this combination of mods.

**Minimal setup needed to reproduce**
- Forge version: 1.15.2 - 31.2.46
- Tetra version: tetra-1.15.2-2.18.1
- Tetra configuration: default, I didn't change anything, similar with other mods.
- Other mods: 
astralsorcery-1.15.2-1.12.11
BiomesOPlenty-1.15.2-10.0.0.366-universal
curios-FORGE-1.15.2-2.0.2.6
DungeonCrawl-1.15.2-2.2.1
mgui-1.15.2-2.1.1
observerlib-1.15.2-1.3.1

**Steps to reproduce**
seed: 157733132531422357
X: 400
Y: 120
Z: 800

Create world with those mods, seed and travel to specified coordinates

![image](https://user-images.githubusercontent.com/6943031/99130077-a5070e00-260f-11eb-8cf6-1899f48c8d03.png)

**Comment by Hiranus** [comment] 2020-11-14 10:07
Additional log, this time only with mentioned mods:
https://pastebin.com/HUCYnFnK

**Comment by Hiranus** [comment] 2020-11-14 10:12
![2020-11-14_10 56 46](https://user-images.githubusercontent.com/6943031/99144899-44f18580-266a-11eb-86d7-0752fdd84d28.png)

**Comment by Hiranus** [comment] 2020-11-14 10:41
I couldn't reproduce it without Astral Sorcery and DungeonCrawl so I created bug reports there too.
https://github.com/XYROC/DungeonCrawl/issues/51
HellFirePvP/AstralSorcery#1452

**Comment by mickelus** [comment] 2020-11-14 17:17
Looks like the crash is caused by JEI in the log, which is supposedly not installed.

**Comment by Hiranus** [comment] 2020-11-14 17:53
With or without JEI it still appears. I tried removing as many mods as possible to limit "this mod could cause it" as much as possible, and I have 3 "culprits". If this would generate anything in log it would be better, but it sadly doesn't. People from Astral Sorcery suspect that it has something to do with server side threads, because client side works fine. Either infinite loop or thread deadlock or something similar. 
If possible, best approach to this issue would be to insert some crazy logging (log message for every function or something similar), but that can be impossible.

**Comment by CompletelySmart** [comment] 2020-12-25 14:34
I have run into this issue as well. I've found it sometimes happens when the mods attempts to generate one of the underground structures. My server log gives me this message a bunch of times: 

> Tried to access a block entity before it was created. BlockPos{x=1664, y=23, z=6266}

At this location I've found that there is a forge hammer structure partly generated.

**Comment by Syrikal** [comment] 2020-12-31 18:06
I've run into this issue a few times. The only mods in the list at the top that I've used are Tetra and Biomes o'Plenty. I'm 90% sure that I've seen this without JEI installed as well.

**Comment by Syrikal** [comment] 2021-01-05 03:24
Found it again. Essentially, I can do whatever I want, but the world doesn't respond- no new chunks load, mobs don't move, blocks don't drop when I break them. It's happened in snowy biomes every time as well, so I'm suspicious of the ruins.

**Comment by Zyachim** [comment] 2021-01-05 19:18
> I have run into this issue as well. I've found it sometimes happens when the mods attempts to generate one of the underground structures. My server log gives me this message a bunch of times:
> 
> > Tried to access a block entity before it was created. BlockPos{x=1664, y=23, z=6266}
> 
> At this location I've found that there is a forge hammer structure partly generated.

Yes! I'm having the same exact issue as OP and I saw this in my logs. I suspect that Ice and Fire is the problem as well, because I couldn't recreate the freeze when I removed it. I adore the mod though so I hope that it's just something else conflicting with Ice and Fire that I can remove.

**Comment by Zyachim** [comment] 2021-01-05 20:25
This might be a temporary fix.
https://github.com/Alex-the-666/Ice_and_Fire/issues/3375

**Comment by mickelus** [comment] 2021-03-09 12:54
Closing. If you still have this issue then comment and let me know that it still persists.

**Closed by mickelus** 2021-03-09 12:54 UTC
Labels: Needs refinement, bug
