### ISSUE TITLE
Compatibility with Project Spartan

### ISSUE THREAD

**Issue by Atlantispy** [mickelus/tetra#522] opened 2021-11-15 14:43 UTC
### Feature description

A mod that provide extra weapons to game. Would be enhanced with compatibility with Tetra

### How it improves the player experience

This mod adds, greater depth into weapon types, and being able to enhance that with features from Tetra would be nice.

### Tetra synergies

It is a natural fit, with room for the unique system tetra has, just with new items.

**Comment by mickelus** [comment] 2021-12-29 02:12
Closing, duplicate of #324

**Closed by mickelus** 2021-12-29 02:12 UTC
