### ISSUE TITLE
[Crash] Something quiver related?

### ISSUE THREAD

**Issue by EightBlade** [mickelus/tetra#59] opened 2019-05-08 03:01 UTC
## Bug Report

https://pastebin.com/kBYA4JG1

It should all be in there. I dunno what happened.

**Comment by Deshiba** [comment] 2019-05-09 10:01
What action were you performing when this crash occurred? This might help narrow down the exact cause.

**Comment by mickelus** [comment] 2019-05-09 13:42
Duplicate of #53, update to 0.25.4 or later.

**Closed by mickelus** 2019-05-09 13:42 UTC
