### ISSUE TITLE
enchantment texture overlaying multiple times

### ISSUE THREAD

**Issue by hitubhg** [mickelus/tetra#544] opened 2022-01-07 09:14 UTC
### Observed behaviour

i know there is an option to disable the glint entirely but im pretty sure u could make it so the texture only renders once, maybe by just applying it to the handle but still having it be on top of all the module textures or something like that

### Expected behaviour

same visual as non modular items

### Steps to reproduce

enchant

### Tetra version

3.20.0

### mGui version

3.3.0

### Forge version

1.16.5 36.2.20

**Comment by mickelus** [comment] 2022-01-07 13:43
Duplicate of #469, closing.

**Closed as completed by mickelus** 2022-01-07 13:43 UTC
Labels: bug
